### ISSUE TITLE
Correlator values are not changing 

### ISSUE THREAD

**Issue by arunk9034** [googleads/videojs-ima#1009]
Hi Team,

I'm using Adx and GPT video ad tags on videojs-ima, But facing the same correlator issue with GPT video tags only, each GPT tag correlator is the same and this is because of GPT display ads, When removing the gpt.js for GPT display ads then it working fine, all correlator value serving diff for each request.

**check out these links** 
1. [Correlator values diff here for each ad request](https://video.unibots.in)
2. [Correlator values same here for each ad request for GPT tags](https://video.unibots.in/client_test.html)

Now I'm explaining to you what is happening, on the first link [(1)](https://video.unibots.in) I'm destroying the ima adManager and after that contentComplete then setting adResponse and then ima ad request, now in this scenario everything is working fine, on each ad request diff correlator values are showing.

now on the [2nd link](https://video.unibots.in/client_test.html), everything is the same except I'm using GPT display ads also on this link, but here each correlator value for GPT tags is the same.
Look at this [video](https://we.tl/t-M1a6EhzEGU) will help you to understand the issue. **check with mute I forget to stop the music in my browser tab.**

**Comment by Kiro705** [comment]
Hi @arunk9034 ,

Thanks for raising this issue. As you've identified it's an issue with the correlator not being reset in GPT, and IMA getting the correlator value from GPT when IMA is reset.

Because this is an issue with the IMA SDK / GPT, and not specific to the videoJS-IMA plugin, would it be possible for you to raise the issue on [IMA SDK forum](https://groups.google.com/g/ima-sdk) for more general assistance? This will insure the bug is raised through the proper channels.

Thank you,
Jackson
IMA SDK team

**Comment by arunk9034** [comment]
Hi @Kiro705 ,

Thanks for your response.

I already created an issue on **IMA SDK forum** you can [here](https://groups.google.com/g/ima-sdk/c/NrffsJXMMEA), I created the issue before 4-5 days, but they can't find the issue yet and still looking for a solution actually, ad Tags response working fine on our [website](https://video.unibots.in/client_test.html) but they always getting **VAST RESPONSE EMPTY ** issue.

So I think this might be a bug of the videojs-ima plugin, that's why I report the issue here also.
