### ISSUE TITLE
Full-slot non-linear ads serving from vmaps breaks the player

### ISSUE THREAD

**Issue by komw** [googleads/videojs-ima#1017]
There is a bug in handling the full-slots non-linear ads inside the vmap files.
When there is a full-slot non-linear ad before the linear ad in the same adbreak, after skipping, or playing the full-slot non-linear ad any videojs-ima player hangs up.

**Example:**
Please use below vmap file:
(there is no difference between breakType linear/nonlinear in the first ad)

`<vmap:VMAP xmlns:vmap="https://www.iab.net/videosuite/vmap" version="1.0">
  <vmap:AdBreak timeOffset="start" breakType="nonlinear" breakId="preroll">
    <vmap:AdSource id="preroll-ad-1" allowMultipleAds="true" followRedirects="true">
      <vmap:AdTagURI templateType="vast1">
      <![CDATA[ https://127.0.0.1:8080/full-slot-nonlinear.xml ]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
  <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
    <vmap:AdSource id="preroll-ad-2" allowMultipleAds="true" followRedirects="true">
      <vmap:AdTagURI templateType="vast1">
      <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
</vmap:VMAP>
`

and the simplified version of full-slot non-linear vast file:
_full-slot-nonlinear.xml_

`<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="4.0">
    <Ad id="521811797728">
        <InLine>
            <AdSystem>AdSense</AdSystem>
            <Creatives>
                <Creative id="562285126470" sequence="1">
                    <NonLinearAds>
                        <NonLinear width="336" height="280" minSuggestedDuration="00:00:30" scalable="false" maintainAspectRatio="false">
                            <StaticResource creativeType="image/jpeg"><![CDATA[https://tpc.googlesyndication.com/simgad/15179307025952348455]]></StaticResource>
                        </NonLinear>
                    </NonLinearAds>
                </Creative>
            </Creatives>
            <Extensions>
                <Extension type="AdSense"></Extension>
            </Extensions>
        </InLine>
    </Ad>
</VAST>
`

Please use samples from above with players directly from https://github.com/googleads/videojs-ima/tree/master/examples -> the player will hangs and stops playing ad/content after playing/skipping the first ad from above vmap file.

It seems that videojs-ima are not triggering the 'ad end' event in such case, and it stays in 'ad playing' state without changing the current ad to the next one. The ad controls and whole ad overlay stays on the screen( the non-linear ad dissapear) and user cannot do anything because of that strange player state.

**Comment by Kiro705** [comment]
Hello @komw ,

I am having trouble reproducing the behavior you are seeing. Would it be possible to share the exact VAST that causes the error?

I played both VASTs you provided and saw ad playback followed by video playback.

**Comment by komw** [comment]
@Kiro705 its not a separate config,so do not play it separately, but the first file is the Vmap which should use a second VAST tag.

I created a ready VMAP file for you: 
https://cdn.veedmo.com/cdn/samples/ads/player-dev-ads/vmap-fullslot-nonlinear.xml

Its not working with the videojs-ima, also its not working with https://googleads.github.io/googleads-ima-html5/vsi/ 
As I mentioned before: player will play the first AD, but if you will wait to finish this ad, or skip it, the next one won't be played, and the player hags up. There will be still controls from AD overlay etc.
I'm aware that this bug applies to all IMA players on the market :(

**Comment by Kiro705** [comment]
Hello @komw ,

Thank you for creating the completed xml link to test with. I was able to see the behavior with the player stalling after the first ad in both the [videoJS sample](https://googleads.github.io/videojs-ima/examples/advanced/) and [VSI player](https://googleads.github.io/googleads-ima-html5/vsi/).

Since, as you pointed out, this happens for all IMA players, it may be a limitation of IMA. And I would recommend raising this issue on the [IMA technical forum](https://groups.google.com/g/ima-sdk) to surface this for all IMA users.

Looking at the types of ads, it may be an issue with the non-linear ad. IMA expects non-linear ads to display during content playback. See this [sample non-linear ad](https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=). Based on that, this may be a misuse of non-linear ads.
