### ISSUE TITLE
HELP: Ad Rule with autoPlayAdBreaks: false

### ISSUE THREAD

**Issue by mcanjs** [googleads/videojs-ima#1018]
Hi,
I decided to create an ad rules on the player we are using, I do autoPlayAdBreaks: false when starting videojs-ima.
The ad rule I want to make: If the user watched the content for more than 3 minutes, I want to show the ad breakdown in the active time. I want to hide or turn on the ad breakups from VMAP for a while. (Pre roll and post roll will not be included in this rule)
I don't want to show ads for 3 minutes after watching each ad.

Before the pre-roll request plays, I run the command: "this.player.ima.playAdBreak()"
If the ad is over after playing the pre-roll, I trigger the "COMPLETED" event, run "this.adsManager.stop()" and start the timer. After 3 minutes I run "this.adsManager.start()". The request is sent but the ads are not working.

JS: `https://codepen.io/mcannn/pen/XWezXEv`
XML (VMAP) EXAMPLE! : `https://codepen.io/mcannn/pen/rNGYxKE`

**Comment by Kiro705** [comment]
Hi @mcanjs ,

One change I would recommend is getting the ad manager using the [event based method here](https://github.com/googleads/videojs-ima#ima-plugin-ad-events), otherwise the plugin cannot guarantee the ad manager is ready.

Otherwise, I am unsure why your setup would be failing.

Have you tried building a similar IMA implementation without the videoJS plugin? Or are your receiving an error messages as your application runs?
