### ISSUE TITLE
is iOS 7 supported?

### ISSUE THREAD

**Issue by binarystatic** [googleads/videojs-ima#102]
I've been trying to debug a problem with my custom videojs player which only occurs on iOS 7 devices. Using this plugin, after an ad plays, the browser crashes when switching back to the main video. Everything proceeds normally in every other browser tested, including iOS 8 and iOS 6.

Then, testing the 'examples/simple/' setup in your repository, I'm finding that ads don't even play at all on iOS 7, whereas the ads play as normal in iOS 8 and iOS 6.

Is there anyway to get this plugin supported on iOS 7?

**Comment by shawnbuso** [comment]
What devices are you using to test? I tested out the simple sample on an iPad 2 simulator running iOS 7.1 and tested the iPhone sample on a 5s running 7.1 and both are working for me. If you're using an iPhone be sure to use the iPhone sample to test.

**Comment by binarystatic** [comment]
The only physical test device I have running iOS 7 is an iPod Touch 5th gen
on 7.1.2.

Since there's very little in the way of explanatory documentation, why are
the differences in the 'iPhone' sample necessary for iPhones compared to
what's in the 'simple' example? The 'simple' example works fine on my
iPhone 5S running iOS 8.4.1. Is there one solution that works for all
browsers/devices?

**Comment by shawnbuso** [comment]
This is related to https://github.com/videojs/video.js/issues/1432. We detect taps on the video player to request ads, but on iPhone these tap events don't work as expected. For the iPhone example, instead of loading the video player on the page immediately, we load a div where the video player will be and fill in a video preview image. When the div is tapped, we load the video player and request ads.

**Comment by shawnbuso** [comment]
Is the iPhone sample working for you on iOS7? Let me know so I can close this out or look into it further.

**Comment by binarystatic** [comment]
Yes, this is fine, thank you.
