### ISSUE TITLE
Two instances using same correlator

### ISSUE THREAD

**Issue by petronioamaral** [googleads/videojs-ima#1030]
Hi there,

I have two containers (preroll and midroll), with different calls.
Is possible use the same correlator from 1st player to 2st player? (competitive exclusions)

If can be, how works? because when I set the same correlator within two containers is generated different (and new) correlator, I think should generate the same correlator, is it?

thanks in advance

**Comment by Kiro705** [comment]
Hello @petronioamaral ,

I do not believe this is possible, since IMA will always create a new correlator for a new ad request. It is not possible to manually set the correlator. For concerns related to the IMA SDK, not specific to the videoJS-IMA plugin, please see this [case opened on the IMA technical forum](https://groups.google.com/g/ima-sdk/c/sfF2wI4kaaI/m/ACWDzcFyBQAJ).

Thank you,
Jackson
IMA SDK team
