### ISSUE TITLE
Is it possible to override the default ad tag from query params?

### ISSUE THREAD

**Issue by rochapablo** [googleads/videojs-ima#1057]
While playing the ad using `videojs` and `player.ima` I've notice the following parameters (`https://pubads.g.doubleclick.net/gampad/ads?...vpa=click&vpmute=1`)

```
vpa: click
vpmute: 1
```

To that, I would like to know if it's possible to override (https://support.google.com/admanager/answer/7320899?hl=en) this items.

I've tried 

```
player.ima({
    ...
    adTagParams: {
        vpa: 'auto',
        vpmute: null
    },
    cust_params: {
        vpa: 'auto',
        vpmute: null
    }
});
```

but nothing changes.

**Comment by rochapablo** [comment]
Possible related https://github.com/googleads/videojs-ima/issues/772

**Comment by Kiro705** [comment]
Hello @rochapablo ,

These values are set by the sdk, but this is based on how the ad request is built.

To set these values when the plugin builds the ad request, used the following [additional settings](https://github.com/googleads/videojs-ima#additional-settings):

- autoPlayAdBreaks
- adWillPlayMuted

Note: I am unclear why adWillPlayMuted is deprecated, but I don't think there is a plan to remove this functionality.

This issue is unrelated to DAI support https://github.com/googleads/videojs-ima/issues/772.

Thank you,
Jackson
IMA SDK team

**Comment by rochapablo** [comment]
Hello @Kiro705, thank you very much, I'll be looking into this right after lunch.

Thank you again.

**Comment by Kiro705** [comment]
Hello @rochapablo ,

To confirm, the code you are using should look something like this:

```
var imaOptions = {
  adTagUrl: 'YOUR_AD_TAG',
  autoPlayAdBreaks: true,
  adWillPlayMuted: false,
  // any additional options.
};

player.ima(imaOptions);
```
