### ISSUE TITLE
Ad Rule Non linear ad break causes

### ISSUE THREAD

**Issue by mcanjs** [googleads/videojs-ima#1062]
Hello,

I made ad rules through this library and when we added non-linear ads, pre-roll and non-linear were working and no other ads were working.
You can test it from the site link I posted below. After the pre-roll runs, a non-linear ad will appear at the 4th minute. We are using VMAP and this is how we defined the non-linear ad to vmap. The ad request will then not work even if it is filled with VAST XML. I searched a lot but couldn't find a solution.

JS Ad Rule plugin codes: https://codesandbox.io/s/floral-dust-nr6es8?file=/src/index.js
Example VMAP : https://ads-test.dygdigital.com/services/vmap?platform=desktop&site=Puhutv&category=Arrays&section=avlu_Bolum&description_url=https%3A%2F%2Flocalhost%3A3000%2F&target=behzat-c%c-1Cbehz2 -section%2Cbehzat-c-1-section-watch%2C791548%2Csection-video%2C1-season-1-section%2C1-season%2C%2Cstg-test%2Cseries-local-series
Site : https://puhutv.com/avlu-1-bolum-izle

**Comment by Kiro705** [comment]
Hello @mcanjs ,

I'm having a difficult time getting ads with the ad tag you shared.

I also did not see the ad tag from you sample page.

I would recommend the following to debug.

1. Make sure you ad tag has the expected behavior outside of the plugin. Use the [VSI player](https://googleads.github.io/googleads-ima-html5/vsi/) to test.

2. Make sure you are properlly initiating the plugin. Your code should make the following calls:

```
var player = videojs('content_video', videoOptions);

var imaOptions = {
  adTagUrl: 'YOUR_AD_TAG'
};

player.ima(imaOptions);
```

Let me know if you have any questions.

Thank you,
Jackson
IMA SDK team

**Comment by mcanjs** [comment]
Hello again @Kiro705,

I tested VSI player but since content length 1 minute I don't tested successfully.
I applied your tricks but not changed result.
I can't send any test link at the moment, because of this problem, we changed the structure completely.
I applied
