### ISSUE TITLE
Getting "player.ima is not a function"

### ISSUE THREAD

**Issue by yashraj-02** [googleads/videojs-ima#1073]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/75726876/209623244-7348f2be-5dd6-4b7b-8c82-14ca3b62cfae.png">

I am getting the `player.ima is not a function` error. Basically, I have added try catch to the entire function & the catch block is helping me to log the messages to my logging service.

My guess is that the function` [new ImaPlugin(this, options);]` is not getting attached [to the player.ima] till the time I call `player.ima(options)`
<img width="495" alt="image" src="https://user-images.githubusercontent.com/75726876/209623685-b728d2d5-058d-4cd7-8228-ea9fb0887567.png">

**Callstack**
```
TypeError: player.ima is not a function
    at setUpVideoJS (https://cdm.xyz.com/video.js:6093:10)
    at setupPlayer (https://cdm.xyz.com/video.js:6028:16)
    at insertPlayer (https://cdm.xyz.com/video.js:6016:10)
    at Object.bootstrap (https://cdm.xyz.com/video.js:6007:10)
    at https://cdm.xyz.com/42547/xyz.js:21:361824
    at video.cmd.push (https://cdm.xyz.com/video.js:75196:5)
    at https://cdm.xyz.com/42547/xyz.js:21:361783
    at u.push (https://cdm.xyz.com/prebid/pb.42547.1664965310891.js:4:416)
    at r (https://cdm.xyz.com/42547/xyz.js:21:361432)
    at e (https://cdm.xyz.com/42547/xyz.js:21:362404)
```

**Comment by yashraj-02** [comment]
Anyone?

**Comment by dioramayuanito** [comment]
https://github.com/googleads/videojs-ima

```
    <!-- Load dependent scripts -->
    <script src="/path/to/video.js"></script>
    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
    <script src="/path/to/videojs-contrib-ads.js"></script>
    <script src="/path/to/videojs.ima.js"></script>
```

maybe ima3.js is missing from your script?

**Comment by yashraj-02** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/75726876/209759412-69806c26-156a-4f4b-8d3f-e6fd085cc636.png">
Nope. It is present.

**Comment by yashraj-02** [comment]
@dioramayuanito

**Comment by Kiro705** [comment]
Hello @yashraj-02 ,

Would it be possible to reproduce this error using the plugin's [sample apps](https://github.com/googleads/videojs-ima/tree/main/examples)?

Depending on where the try/catch is implemented, player.ima() may not be available.

Thank you,
Jackson
IMA SDK team

**Comment by yashraj-02** [comment]
That’s the problem. The error is not reproducible on my side either. I am seeing this in error logs sent from client side from the actual users.

**Comment by dioramayuanito** [comment]
> That’s the problem. The error is not reproducible on my side either. I am seeing this in error logs sent from client side from the actual users.

I have a feeling that your users "maybe" enabled an Ad Blocker

**Comment by yashraj-02** [comment]
@dioramayuanito 
Nice guess but that's not the case either. Because the core script [which calls videojs & videojs-ima] gets blocked if an ad-blocker is present on the page.

**Comment by yashraj-02** [comment]
@Kiro705 @dioramayuanito

**Comment by gschoppe** [comment]
> the core script (#script_1) gets blocked if an ad-blocker is present on the page.

It is important to keep in mind that many different ad blockers exist, and may have completely different blocklists or fingerprints that they use to block certain resources. Just because one ad blocker prevents your #script_1 from loading does not mean that all will behave the same.

That said, `player.ima` is first instantiated by the call on [line #3778 of videojs-ima.js](https://github.com/googleads/videojs-ima/blob/11ecbefa37fbdbd6877fece63c38c11338b9e913/dist/videojs.ima.js#L3778).

The operations that need to occur for `player.ima` to exist are as follows:

* `videojs` must be loaded
* line #3778 of `videojs-ima.js` must have already been called
* `player` must be an instance of the `videojs` player object

If those conditions are all met, `player.ima()` will exist. On first call, it will create an instance of the `ImaPlugin` class. On subsequent calls, it will return the existing instance of `ImaPlugin`. This "singleton-esque" behavior is what is occurring in the `Init` function that you mentioned in your first post.

I would recommend testing your base assumptions by adding explicit logging code to verify each of the prerequisites that I listed above. I'd be willing to bet that for users who cannot access `player.ima`, at least one of those bullets is false.

Thanks,

Greg Schoppe
IMA SDK Team

**Comment by yashraj-02** [comment]
Thanks.

Also, I raised this in videojs forum also. They recommended me to rearrange the imports this way.
`video.js first, then contrib-ads, then ima`

Currently, my imports are organized in this manner
<img width="571" alt="image" src="https://user-images.githubusercontent.com/75726876/210166335-cbd6edd0-01bf-4774-a26a-f9cc60d7826d.png">

Do you have any take on this?


Link to slack thread: https://videojs.slack.com/archives/C43LGP955/p1672309629213189?thread_ts=1672124949.828749&cid=C43LGP955

**Comment by gschoppe** [comment]
You definitely should reorder your imports, as they described, so as to match the order shown in the videojs-ima README file.

**Comment by yashraj-02** [comment]
Thanks @gschoppe. I am implementing this changes. I will update you guys here after we have the data in few days.

**Comment by yashraj-02** [comment]
Do you guys have any idea regarding why does `player.ima` gets converted into an object later? Like, initially it's a function but after a few milliseconds, it gets converted to an object.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/75726876/210234293-39027732-fff2-4f76-996e-edbd77cce361.png">

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/75726876/210234433-b6cfa3e0-bc4b-4384-9713-121293274417.png">

**Comment by dioramayuanito** [comment]
do you initialize videojs-ima more than once? for multiple player?

**Comment by yashraj-02** [comment]
Yup, I did that.

**Comment by gschoppe** [comment]
> Do you guys have any idea regarding why does `player.ima` gets converted into an object later? Like, initially it's a function but after a few milliseconds, it gets converted to an object.

This is standard behavior for videojs plugins. You can read more about it in the [videojs documentation](https://videojs.com/guides/plugins/#the-player-plugin-name-property).
