### ISSUE TITLE
ima sdk iframe not loading, stopping player loading

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1100]
This is related to the "black box" isue we talked about before Jackson @Kiro705 .  I think i've now pinned it down more.  I see that every time the "black box" happens the ima sdk isnt loading the iframe, that is usually there, this:

![DevTools_-_127_0_0_1_5502_prebid_VideoDemo_DemoSite_pages_playlistUIvertical_html](https://user-images.githubusercontent.com/8503167/236528570-ece499c9-dbab-48c8-b5c8-db5c7598aad3.png)

On every "good page load, this iframe is there, on every "bad" page load/ black box, this iframe isnt there and when its not there, its stopping the player from loading propely, as if its "no iframe load" can't continue.  Any idea on how to fix this, as it seems a ima sdk problem and/ or a way videojs-im is interacting with ima sdk maybe.  There still no errors etc, juts purely this iframe not loading

**Comment by Kiro705** [comment]
Hello @spormeon ,

If this is related to a previous issue, please feel free to continue that thread. For this issue, do you have a way to reproduce it reliably? Please include any relevant information or steps. Otherwise, it may be difficult to identify a fix for the issue.

Thank you,
Jackson
IMA SDK team
