### ISSUE TITLE
The question icon (why this ad CTA) is not clickable

### ISSUE THREAD

**Issue by sunny0901** [googleads/videojs-ima#1105]
Hi there,

As red circled on the bottom-right of the screenshot below, the little question icon (why this ad CTA) is below the ad controls overlay and can't be clicked. Could someone help me here?
<img width="995" alt="Screenshot 2023-05-24 at 10 14 15 PM" src="https://github.com/googleads/videojs-ima/assets/42742286/30aed068-e4e5-4f3f-8a11-e1b33d73ad5a">

**Comment by Kiro705** [comment]
Hello @sunny0901 ,

Would you be able to provide any steps to reproduce this issue? Is it reproducible on the [videoJS-IMA plugin samples](https://googleads.github.io/videojs-ima/)?

If you would like to privately share the ad tag, you can email jsui@google.com.

Thank you,
Jackson
IMA SDK team

**Comment by sunny0901** [comment]
Thanks Jackson! Yes, it's can be reproduced and I've sent the tag url to you email.

**Comment by Kiro705** [comment]
Hello @sunny0901 ,

This ads call to action (CTA) is the "Shop now" button in the upper right, and that remains clickable. The question mark icon is the "About this ad" icon, and is meant to provide information to users on how this ad was chosen for them, I can confirm that it is not clickable based on the videoJS-IMA plugin control UI.

Typically, IMA does not expect icons in this area of the video player, but it should be possible to create a work-around by altering the css for the videoJS-IMA controls. There is also the `disableAdControls` [additional setting](https://github.com/googleads/videojs-ima#additional-settings) which can hide the ad video controls. However, this "About this ad" icon is still partially un-clickable, and would require some css changes.

What is your expected behavior regarding this issue?

Thank you,
Jackson
IMA SDK team

**Comment by sunny0901** [comment]
Hi Jackson,

The expected behaviour is to get the "About this ad" icon clickable. Currently it's just look like a bug. And we do want to show the ad controls to users, so hiding controls is not ideal.

I also tried updatinng the css of the "About this ad" icon, but since it's nested inside an iframe, getting access to the element is very hackey and difficult. 

I did a lot of search online but didn't find anything useful. I was wondering why this is occurred to us only. 🤔 And also how we could get control over this "About this ad" icon?

Thanks!

**Comment by Kiro705** [comment]
Hello @sunny0901 

It is likely you will not be able to move the "About this ad" icon. Also, doing so may be against the ad providers policy, I would recommend reaching out to them for more info.

Other options for your app could include changing the control bar's css to avoid overlapping the icon.

Let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team

**Comment by kagrela** [comment]
@sunny0901 did you end up with solution for above? Right now I'm trying to fix it because of DSA compliance.

>Other options for your app could include changing the control bar's css to avoid overlapping the icon.

@Kiro705 could you propose some control bar's css changes for it? As I wrote now for us it's about being DSA compliant :)
