### ISSUE TITLE
reset IMA tag

### ISSUE THREAD

**Issue by DuongDD317MIrabo** [googleads/videojs-ima#1118]
Hello everyone,

I'm currently facing an issue with reloading advertisement videos when replaying the main video. I'm getting an error message "VIDEOJS: WARN: Unexpected adsready event" when I reset the IMA (Interactive Media Ads) plugin using the following code:

this.player.ima.changeAdTag(adTagUrl);
this.player.ima.requestAds();

Can you please help me with this? Thanks.

**Comment by Kiro705** [comment]
Hello @DuongDD317MIrabo ,

Thank you for raising this issue. My understanding is you would like to play ads when users replay a video. I do not believe this functionality is directly supported by the IMA SDK or this plugin. The expectation is a user can replay a video they have already watched, without the need to watch ads again.

If this behavior is required, you may be able to completely remake the player with the same content, instead of replaying the content on the original player.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
