### ISSUE TITLE
Main content loads before the ad on preroll 

### ISSUE THREAD

**Issue by kashiph001** [googleads/videojs-ima#1122]
Hi ,
I have an issue in which the main video loads for 0.5 sec then after the ad will play ,  I want the functionality in which ima-ad play before the main content.
I have use videojs , video-contrib-ad and videojs-ima.

**Comment by Kiro705** [comment]
Hello @kashiph001 ,

This is a result of IMA client-side ad playback, where ads are only loaded when requested by the IMA. A work around could be to use CSS to not display the content video player, until a preroll ad has been loaded.

Another alternative, would be to use [IMA DAI](https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai), which allows for playback of an ad and content stitched stream, so that only a single media source is used.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
