### ISSUE TITLE
( not issue ) Can i call dfp ad video Without video content On pop up.

### ISSUE THREAD

**Issue by baqarrivi** [googleads/videojs-ima#190]
Actually i want to call my video add player at the pop up . is it possible if yes then how. i am using video.js and its working fine .!

**Comment by shawnbuso** [comment]
I'm a bit confused - what are you going for? You want to play a video ad, but you don't have any video content? You can use this plugin for that, but it's a bit overkill - you'll be loading a ton of stuff you don't actually need if you're not playing any video content. Also when the ad ends you get a loading spinner in the player because it's trying to load content even though you haven't provided a source. The plugin isn't really set up to do this as it is today, but it's possible for you to modify it to make it work. You'd want to add another method so you can provide an ad ended listener (like we have now for content ended and ads-and-content ended) and call that listener when the ad ends. In that listener you could hide the video player so you don't just see a loading spinner. Let me know if I understood your question correctly and if all that makes sense.

**Comment by baqarrivi** [comment]
Hello shawnbuso,
1 ) I want to call **only advertisement** player first at the download button. as a pop up 
2 ) After ending add the download should start .

Please find an image here for more help you are always responsive for me . 
https://drive.google.com/file/d/0B4I-4WmjYzMvMWtCakY0Wnc0UnM/view

**Comment by shawnbuso** [comment]
OK, I don't think what you want to do is possible with the video.js IMA plugin. The plugin is pretty dependent on you having some content video to play - without wanting to play content, it doesn't make sense to use the plugin, because it will still load and display the content player. It might make sense for you to try this using the IMA SDK without the plugin. You can find our documentation for that [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/).
