### ISSUE TITLE
IMA SDK does not work on HTC One

### ISSUE THREAD

**Issue by jdp** [googleads/videojs-ima#221]
Using an HTC One running Android 4.3, using the stock browser, the IMA SDK raises this error:

> Unsafe JavaScript attempt to access frame with URL http://googleads.github.io/googleads-ima-html5/advanced/ from frame with URL http://imasdk.googleapis.com/js/core/bridge3.127.2_en.html#goog_1021611025. Domains, protocols, and ports must match.

It prevents the video from playing. I reproduced on the [IMA HTML5 SDK Advanced Demo](http://googleads.github.io/googleads-ima-html5/advanced/) with the sample ad tag.

**Comment by shawnbuso** [comment]
We've had problems on all mobile web with the standard samples - have you tried the [iPhone sample](http://googleads.github.io/videojs-ima/examples/iPhone/)? If you're still seeing the error there then we'll need to look into this further. Thank!s

**Comment by jdp** [comment]
The iPhone sample does play. What are the key differences between the two samples that cause one to work but not the other?

**Comment by shawnbuso** [comment]
The big difference that makes it work on Android is that it doesn't rely on the "tap" method of the video.js player, which has been hit or miss as of late. 

Another big difference is that it doesn't put the video player on the page at load, it builds it as a result of the user tapping on the poster image. We've had some issues with video player initialization in the past when we tried to do it on page load, so that ensures that it happens a) after the page has loaded, and b) as the result of a user action.
