### ISSUE TITLE
IMA plugin keeps requesting more ads after adend event

### ISSUE THREAD

**Issue by yukster** [googleads/videojs-ima#244]
We recently rolled out using the videojs-ima plugin on our games website to show preroll ads before the game loads. Throughout testing and for the first few weeks, everything was working fine. But in the last few days, we've been seeing a runaway ad process continuing to make ad ajax calls and throw errors after the adend event has already fired and we've switched over to the game. These calls and errors often get bad enough that the browser freezes up and crashes.

Looking through the IMA SDK docs, I see that there are 'destroy' methods on a couple of their objects. One explicitly says that the SDK will be unloaded and no further calls will be made:

https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdDisplayContainer.destroy

I do not see anyplace that this is exposed in the videojs-ima API however. Is there a method we should be calling on the IMA plugin to turn it off after an ad is finished (or in the event of an adserror event)?

**Comment by shawnbuso** [comment]
Are you playing any content video, or just using this to display ads before the game? If the latter, it's a it outside the scope of the plugin. The plugin is intended to be used with the video.js player to show video ads alongside video content. It might make more sense for you to do an IMA integration of your own on the site for your use case instead of using the plugin, but if you have a page I could look at to see the issue I may be able to offer some suggestions on how to fix the problem.

**Comment by yukster** [comment]
Turns out this was a red-herring. Switching to the IMA video.js player was a very recent change for us, so when we started seeing lots of VPAID or VAST ajax calls and console logging, we assumed it was the IMA player doing that. But it turned out that an entirely separate ad on the page was causing the issue. We're talking with that ad network to get that better behaved. Sorry for the noise!
