### ISSUE TITLE
ads not working on iOS

### ISSUE THREAD

**Issue by jamsterdam29** [googleads/videojs-ima#256]
I am still seeing issues playing ads on iOS devices as referenced in issue #134. 

I have tested with the iPhone sample and it plays the source video, however no ads are played.  I am unsure if it is configured for ads.

When i try to play a preroll ad on iOS, I see the "Blocked a frame with origin" issue, although I am not sure it is fatal.  Either because of, or in addition to that error, I never see the ad load or play, and it never throws an error.  I've tried forcing an error to allow the original source video to play, but that does not work either.

Any help would be appreciated.

Thanks, Jeff

**Comment by mkhazov** [comment]
+1

Ads not working on iOS Safari due to CORS issue 
`Blocked a frame with origin "https://imasdk.googleapis.com" from accessing a frame with origin "https://googleads.github.io". Protocols, domains, and ports must match.`

As a result `#ima-ad-container` is not hidden and player controls are not working. It's a serious bug because the user loses the control over the player.

**Comment by mkhazov** [comment]
Flowplayer ima3 plugin ([source code](https://releases.flowplayer.org/vast/flowplayer.org/1.0.2/vast.min.js)) [works fine on iOS](https://flowplayer.org/docs/vast.html#video-advert-examples). As I understand it uses some tricks to handle Vast support on Android and iOS devices - maybe these hacks should be used in this plugin too.

**Comment by shawnbuso** [comment]
Are you testing with the samples hosted on gh-pages for this repo? It looks like they were a bit out of date so I just updated them. I tested the [simple](http://googleads.github.io/videojs-ima/examples/simple/), [advanced](http://googleads.github.io/videojs-ima/examples/advanced/), and [iPhone](http://googleads.github.io/videojs-ima/examples/iPhone/) samples on an iPod touch and all are working now. If you're still seeing issues let me know. If you modify the sample tag in those samples to add your own tag, it could be that your ad server is returning ads that aren't supported on iPhone, so please send along your tag if that's the case. Thanks!

**Comment by mkhazov** [comment]
Tested again, and yes, I have issues with this vmap tag: https://vast.life.ru/api/vmap.xml?domain=life.ru

Hiding `#ima-ad-container` before call to player.ima.startFromReadyCallback() helps me to avoid blocking player controls.

**Comment by shawnbuso** [comment]
I think the first error is a red herring - we see that in a lot of iPhone implementations and we're still tracking down the root cause, but it hasn't been affecting ad playback on other sites. I am also seeing this error however:

[Error] XMLHttpRequest cannot load https://vast.life.ru/api/vmap.xml?domain=life.ru. Origin http://imasdk.googleapis.com is not allowed by Access-Control-Allow-Origin. (x2)

which means the ad request is failing because the ad server isn't set up to allow our SDK to request data. You'll need to get imasdk.googleapis.com added to the Access-Control-Allow-Origin header for vast.life.ru. Are you seeing blocked player controls on iPhone or iPad? In either case that should be fixed with the plugin at HEAD, but you could be hitting an edge case that we haven't yet seen.

**Comment by mkhazov** [comment]
@shawnbuso headers are set for https, so it works on https://googleads.github.io/videojs-ima/examples/advanced/

**Comment by mkhazov** [comment]
I checked all examples on iPad (iOS 9.3.4) - only the [iPhone](https://googleads.github.io/videojs-ima/examples/iPhone/) example works, video won't play in others.

**Comment by shawnbuso** [comment]
Are you seeing additional issues on top of the post-roll issue that we need to discuss here? If not I'll close this out and move the discussion to #265

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still seeing issues please feel free to re-open. Thanks!

**Comment by tonykor** [comment]
I have the same problem, i can't play third party vast ads due to  

Origin http://imasdk.googleapis.com is not allowed by Access-Control-Allow-Origin. (x2)

And i have no access to the ads broker hosting, which serves vast file, to allow this host there. Is there a way play ads from third party ads provider who doesn't allow this host in their serve config files?

**Comment by shawnbuso** [comment]
Hey there,

Unfortunately not - this isn't an IMA SDK thing, it's a web security thing. The SDK is trying to read data from that server, and the server is telling it it's not allowed - a workaround to this would be a pretty big web security vulnerability.

Thanks,
Shawn
