### ISSUE TITLE
Cleaning up player in 'adend' callback too early for tracking pixels to fire

### ISSUE THREAD

**Issue by yukster** [googleads/videojs-ima#259]
I'm using video.js and the videojs-ima plugin to show video ads before games. I register an onComplete callback called on the 'adend' event. It removes the video.js player and loads the game. 

However, an ad partner let us know that their 'ad complete' pixel wasn't being requested. After some debugging, I found that I could get the tracking pixel to load if I made the cleanup code wait a second. I'd rather not guess, however, but I was unable to find a later event in the code.

Has anyone else run into this issue? Is there a better workaround than just wrapping the onComplete code in a setTimeout?

**Comment by shawnbuso** [comment]
This is a bit tricky because the plugin isn't really intended to be used for this use case - loading the whole video.js player without actually having content to play is pretty overkill. You might be better served by doing an IMA SDK integration directly on your page rather than through the plugin. You can follow the guide [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/quickstart) to get it integrated. You'll still need to create a content player, you just won't be playing any content, and it'll be much faster and more lightweight than loading the whole video.js player.
