### ISSUE TITLE
AdError 501 with forceNonLinearFullSlot

### ISSUE THREAD

**Issue by palcoder** [googleads/videojs-ima#270]
Hi,

I have used forceNonLinearFullSlot option to render ads on full player width. It works fine on the preroll with text ads but it does not work in midroll and cause the error "AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area.".

I tried to find a solution to this issue but cannot find any useful info and my workaround to set nonLinearWidth and nonLinearHeight to the payer dimensions is failed.

Thank you

**Comment by shawnbuso** [comment]
Hi there,

Could you provide the tag you're using to test so I can replicate on my end?

Thanks!
Shawn

**Comment by palcoder** [comment]
Hi,

Here is the tag I used:

`http://googleads.g.doubleclick.net/pagead/ads?ad_type=skippablevideo_text_image_flash&client=ca-video-pub-3701526372767426&description_url=[description_url]&hl=en`

I noticed the error appeared only when I enabled text ads for the midroll. Also, I cannot set the IMA to request creatives larger than 480x90 (ex: 300x250) to be rendered as a full slot even I use forceNonLinearFullSlot

Thank you

**Comment by shawnbuso** [comment]
Ah ok - how are you serving this as a mid-roll? The tag as it is is just a single ad, so it would display as a pre-roll. If you've got some sample code I could take a look at that would be great. Thanks!

**Comment by palcoder** [comment]
I was wrong. The issue that the full slot overlay can be shown only once. If another ad will appear as a full slot, the sdk throw the AdError 501. 
Here is a test code:

```
var player = videojs('content_player');
var adTag  = 'http://googleads.g.doubleclick.net/pagead/ads?ad_type=skippablevideo_text_image_flash&client=ca-video-pub-3701526372767426&description_url=[description_url]&hl=en';

player.ima({id: 'content_player', debug: true});

var requestAd = function(adTagUrl) {
	// Destroy Ads Manager
	if (player.ima.getAdsManager()) {
		player.ima.getAdsManager().destroy();
	}

	player.ima.initializeAdDisplayContainer();
	player.ima.setContentWithAdTag(null, adTagUrl, true);
	player.ima.requestAds();
};
		
var adPreroll = function(){
	// Start ads when the video player is clicked, but only the first time it's clicked.
	var startEvent = 'click';
	if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/Android/i)) {
		startEvent = 'touchend';
	}

	player.one(startEvent, function() {
		// Request the preroll ad tag
		requestAd(adTag);

		// Start the video playback
		player.play();
	});
};

var adMidroll = function() {
	var midrollAdBreaks = [30];
	
	player.on('timeupdate', function(event) {
		var duration = player.duration();
		var currentTime = player.currentTime();

		if (midrollAdBreaks && midrollAdBreaks[0]) {
			if (currentTime > midrollAdBreaks[0]) {
				requestAd(adTag);

				// Reset current time
				player.currentTime(currentTime);
				player.play();

				midrollAdBreaks.shift();
			}
		}
	});
};

adPreroll();
adMidroll();
```

**Comment by shawnbuso** [comment]
Hmm I tested your code but it's working for me - I see an overlay pre-roll and then a skippable ad at the mid-roll. I just took your code here and dumped it into the ads.js file for the simple example. Are you using the latest version of the plugin? It could be that you're running into an old bug that has since been fixed.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still seeing an issue please feel free to re-open. Thanks!

**Comment by dannyf620** [comment]
Everything is working well, ads work ok but when the screen of the user is too small it return an adError (503), I made a change in the Advance example [Advanced Example](https://googleads.github.io/videojs-ima/examples/advanced/) resizing the iframe that contain the ad, “this example is **not responsive**, it was the one simple way to replicate the error (501)”

Uncaught AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area.

In the IMA API documentation  there is a const for the error but I can not handle this error. 
In the event array i add two events and modify the onAddEvent .
the tag of @palcoder  is a perfect sample. 

```
Ads.prototype.SAMPLE_AD_TAG = 'http://googleads.g.doubleclick.net/pagead/ads?ad_type=skippablevideo_text_image_flash&client=ca-video-pub-3701526372767426&description_url=[description_url]&hl=en';
 var events = [
 ...
    google.ima.AdEvent.Type.NONLINEAR_DIMENSIONS_ERROR,
    google.ima.AdErrorEvent.Type.AD_ERROR
  ];
```

```
Ads.prototype.onAdEvent = function(event) {
  var message = 'Ad event: ' + event.type;
  this.log(message);
  var resizeInterval;
  if (event.type == google.ima.AdEvent.Type.NONLINEAR_DIMENSIONS_ERROR || event.type == google.ima.AdErrorEvent.Type.AD_ERROR) {
    console.log("Minimal dimention at: ", document.querySelector('#ima-sample-videoplayer iframe').style.width)
    clearInterval(resizeInterval);
  }
  if (event.type == google.ima.AdEvent.Type.STARTED ) {
    var p = 100;
    resizeInterval = setInterval(function () {
      document.querySelector('#ima-sample-videoplayer iframe').style.width = (p--) + '%';
    }, 100)
  }
};

```
[fork commit](https://github.com/dannyf620/videojs-ima/commit/b4707136e7a9c5bcab9bd867731c46dd4ff9edba)
- It would can listen the NONLINEAR_DIMENSIONS_ERROR event?

- Can I change the imaOption "nonLinearWidth" and reload ads "player.ima.requestAds();"?

- Or can I detect Ads media (video can resize) (Image force first Styles) "for last instance
See"

**Comment by shawnbuso** [comment]
The way it's set up right now we assume you want to show the video ad it's current size, so if the display area is too small for the ad that gets returned we just throw it out. Are you looking for the player to do something different instead when this happens?

**Comment by dannyf620** [comment]
with the videos ads work the problem is with the image ads, when ad start it push to image but if the player is resize to small that the ad, ocurre a NONLINEAR DIMENSIONS ERROR
please update until you see an advertisement like [image Ad](https://github.com/dannyf620/videojs-ima/blob/5985455a11948cca9ad43fd37fba4cc6eba96ca0/examples/image%20ad.png)
I do not know the name of this type of advertising
Thanks

**Comment by shawnbuso** [comment]
Ah ok this is a full slot ad - so it sounds like you're saying your issue is you get a full slot ad, while it's displaying the video player resizes to be too small for the ad, then you get an error. Is that right? In this case we need to listen for NONLINAR_DIMENSIONS_ERROR alongside AD_ERROR to go back to the content video. We can't force the ad to play if the SDK is telling us that the display area is too small for the ad, but we should at a minimum gracefully fall back to content.

**Comment by dannyf620** [comment]
I use this const google.ima.AdErrorEvent.Type.AD_ERROR but it never triger, the AD_ERROR is not in google.ima.AdEvent ¿this is the correct implementation?

**Comment by dannyf620** [comment]
on scroll down I put video in position absolute to make a floating effect
[video like floating](https://www.rcnradio.com/colombia/region-central/asi-son-los-edificios-que-ordenaron-demoler-en-tunja)

I am going to try to reload ad before the resize player

**Comment by shawnbuso** [comment]
Aha ok I see what you're saying - in this case if the player is sent to the smaller size while an ad is playing, and the new player size is too small for the ad, it should just proceed to content without issue, which is what I'm seeing when I test your page.

**Comment by dannyf620** [comment]
To solve the problem we spoke with our DFP account manager to program the content always of the same type video/mp4 and will not return empty VAST.

But the Overlay and Full-slot should work perfectly if the DFP creative is configured with multiple dimensions and you must have the correct dimensions in the player to play.

something funny is that to listen to the event adError with an addEventListener I had to comment on the line of code in the library `videojs.im.js`
> this.adsManager.addEventListener (google.ima.AdErrorEvent.Type.AD_ERROR, this.onAdError.bind (this));

And move the callback to the interruption in my code

>this.player.ima.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR,function(typeError){...})

**Comment by shawnbuso** [comment]
Thanks for the follow up - is the new set up working for you, or are you still seeing issues?

**Comment by dannyf620** [comment]
that's how it works for me

**Comment by shawnbuso** [comment]
Great, thanks! I'll mark this as closed - feel free to let us know if you run into any more issues.
