### ISSUE TITLE
Preloading Ads

### ISSUE THREAD

**Issue by zshenker** [googleads/videojs-ima#271]
Hi,

I am trying to use preloading that is supported by the IMA SDK, when I set enablePreloading = true on the AdRenderingSettings, I see the media being preloaded (looking in Chrome Dev Tools, Network panel), but then when I click play, the ads fail to play and the content starts playing immediately.

I am not seeing any javascript errors. My videojs-ima options config is as follows:

```
var options = {
  id: 'my-video',
  adTagUrl: adTagUrl,
  adsRenderingSettings: {
    enablePreloading: true
  }
};

player.ima(options);
player.ima.requestAds();
```

Is there something I am doing wrong here, and/or any intention to support pre-loading of ads?

Regards,
Zac

**Comment by shawnbuso** [comment]
Hi there,

Do you have a sample page I could take a look at? I tested in the samples here and it's working, but that's not really preload because we don't send the ad request until you click the play button.

Thanks,
Shawn

**Comment by zshenker** [comment]
@shawnbuso Just setup a sample page at https://zshenker.github.io/videojs-ima/examples/preload/

It calls requestAds() right after the player.ima() setup call.

**Comment by shawnbuso** [comment]
Thanks for the sample. I see a few issues here combining to create this problem. The first is that the contrib-ads plugin that we use has a built in preroll timeout that defaults to 100ms. That timeout spans adsready to ad playback. When we load the VAST response, we fire adsready, and if it takes us more than 100ms to play the ad after that, the plugin will drop it. This will happen basically every time you try to preload, so I extended that to 10 seconds to test further.

After making that change, for some reason preloading in the IMA SDK just flat out fails - when I call adsManager.start() it does nothing, and eventually that 10s timeout fires and we play content. That I'll need to investigate further with the IMA team to see why ads are failing to play. As soon as I have more info on that I'll let you know.

**Comment by zshenker** [comment]
Hi @shawnbuso, just wanted to followup on if you had any updates from the IMA team on what could be causing the ads not to play?

**Comment by shawnbuso** [comment]
I'm still looking into this one but I will let you know as soon as I have more info.

**Comment by zshenker** [comment]
Any updates from the IMA team on this @shawnbuso ?

**Comment by shawnbuso** [comment]
Unfortunately no updates yet - I'm still looking into it but haven't found the cause.

**Comment by cejanik** [comment]
Hi @shawnbuso - any update?

**Comment by cejanik** [comment]
@shawnbuso I've created a new sample page based on the advanced sample code: https://cejanik.github.io/googleads-ima-html5/advanced/

The flow is to make an ads request, enable preloading, wait 5 seconds, then play the ad.

Using the sample ad tag, this appears to work, however the "Ad event: loaded" does not happen until the 5 second timeout is done.
Using the IGN ad tag, it doesn't work at all, however we do see "Ad event: loaded" shortly after "Ads Loaded". Our ads request will return an Ads playlist rather than a VAST tag.

**Comment by shawnbuso** [comment]
When are you calling adsManager.init()? I think the issue is that the SDK won't start loading the ad until you make that call, and as it's set up right now I don't think it will make that call until after the timeout. For more info you can check out the IMA SDK docs on preloading [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/preload).

**Comment by cejanik** [comment]
Thanks Shawn. I've updated my sample to call adsManager.init(), then wait 5 seconds to call adsManager.start() and ads are playing.

I've also updated the IGN ad tag to play a rotation of VAST & VPAID ads. The 3 VPAID do play, but the interactive elements are not present. Is that an expected side effect of preloading VPAID? Do you have any advice for handling preload when the ad type is not known ahead of time?

**Comment by shawnbuso** [comment]
I just took another look at your page - are you still using the video.js plugin? It looks like your current test page is a clone of the IMA SDK advanced sample, which is using the IMA SDK but not the plugin from this repo.

**Comment by cejanik** [comment]
We're not using the plugin. SDK support had previously referred us here, so I've been following up concurrently with you and with them.
My goal is to conclusively determine that preloading will or won't work. If it works with the plugin or on sample code (using Ad Playlists and VPAID ads), it should work for us too.

**Comment by shawnbuso** [comment]
Hmm ok, this issue tracker is really only intended to support the video.js plugin - for support with your own implementation of the IMA SDK you should use the [support forum](https://groups.google.com/forum/?fromgroups#!forum/ima-sdk). Currently we do not support preloading VPAID, however there is a bug in the SDK where in some circumstances (like in VMAP responses) we treat it as if we do. We're working on resolving that, but the end goal at least in the short term is for VPAID ads to *not* be preloaded, even with enablePreload set - that will only apply to linear video ads.

**Comment by jonvaughan** [comment]
Hi,

I was wondering if since this post there had been any progress on VPAID preloading?  Is this proposed behaviour with not preloading VPAID the current implementation?  We have tried it and have had some issues with the VPAID unit not calling back to the player to say it has loaded, but I don't know if that was a bug in the ad.  

Apart from this, in terms of ad loading, anyone have any tips or best practices on performance?

Thanks

Jon

**Comment by shawnbuso** [comment]
We don't have an update on VPAID preloading yet - we will preload the code for a VPAID ad, but the code won't start executing until the ad break time hits (so if the code is turning around and making another ad request, that won't get preloaded). We're doing this because we can't guarantee that a VPAID ad will behave when we try to pre-load it - we don't want to start code execution early and end up with VPAID ads that play before their scheduled break.

**Comment by jonvaughan** [comment]
Ok np, thanks for getting back to me

**Comment by ypavlotsky** [comment]
This has been fixed in the IMA SDK and works now.
