### ISSUE TITLE
VPAID Creative error

### ISSUE THREAD

**Issue by nstevensdc** [googleads/videojs-ima#274]
Hi,

We're getting an error with a known-working ad:

**Ad error: AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info. Caused by: Error: Error: null**

This is an ad URL that is currently working within JWPlatform, but is unfortunately erroring out with videojs + videojs-contrib-ads + videojs-ima.

You can see what we're running into here:

http://feature.dailycaller.com/vidtest.html

When I use the same code with the test ad from the google-ima sample, it's working:

http://feature.dailycaller.com/vidtest2.html

So it seems there's some specific incompatibility between what the ad expects (and gets from JWPlatform), and what it gets from videojs-ima.

I *think* we're pulling ads from networks so there's no contact with any developers I can make, but I'm confirming this with our ad team.

**Comment by shawnbuso** [comment]
Hi there,

It looks like your ad requires insecure VPAID mode, which you can enable in your plugin options with 

    vpaidMode: google.ima.ImaSdkSettings.VpaidMode.INSECURE

Even with that though, I'm seeing an error from the ad itself, do you know what could be causing this within the ad?

"AdOnLoad ERROR!! Error: swfobject failed to create object in element"

**Comment by nstevensdc** [comment]
Thanks for the vpaidMode suggestion. I'll add that.

As for that other part, I'm not sure.  Ad guy confirmed we're using network ads for these.

**Comment by nstevensdc** [comment]
Looks like setting the mode to INSECURE is still leading to security issues:

XMLHttpRequest cannot load http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=is&c=23&pl=VAST&pli=16538558&PluID=0&pos=4677&ord=1726378819&cim=1. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://imasdk.googleapis.com' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

That's what I'm now seeing in http://feature.dailycaller.com/vidtest.html

**Comment by shawnbuso** [comment]
I don't think this is a result of the INSECURE setting, I just think you might be getting further into your ad execution that you did before so you weren't seeing this before. I know it seems like it would be a result of INSECURE because now you're getting a security error, but what this is saying is that you're using a wildcard in your Access-Control-Allow-Origin header on the ad server, and that's not allowed because we make our requests using credentials. You'll have to talk to your ad server to get them to explicitly allow imasdk.googleapis.com in their Access-Control-Allow-Origin header.

**Comment by nstevensdc** [comment]
Turns out the ad was actually busted, apologies.
