### ISSUE TITLE
bundle IMA

### ISSUE THREAD

**Issue by qpre** [googleads/videojs-ima#283]
Hello, is there any particular reason why google won't let us bundle the IMA SDK ?
It'd be nice and would simplify a lot of workflows (such as using the plugin with webpack...)

**Comment by shawnbuso** [comment]
By bundle do you mean host yourself? We disallow this because we're regularly pushing updates that we want all users to have - if you miss out on our regular updates, your page could stop working in production at any time.

**Comment by qpre** [comment]
I mean to be able to import both `videojs-ima` and the ima SDK directly in our script (using ES6 imports), thus avoiding an extra network call and simplifying our delivery process.

Also, I don't see how regular updates to the SDK could prevent our code from breaking at anytime. If google breaks a feature on the master, our code will break if it depends on it.
We'd be safer if the project was delivered through npm and could rely on a revision number.

**Comment by shawnbuso** [comment]
It has more to do with security updates and synchronizing with our ad servers - we occasionally make a change on the server that requires a synchronized change to the clients. If one or more clients aren't updating, those clients could break because they're using an old version of the client script with a new version of the server. I understand your concerns, but we still have to advise that you do not package the IMA SDK with your web page or app.
