### ISSUE TITLE
VPAID not working properly

### ISSUE THREAD

**Issue by AlexMurm** [googleads/videojs-ima#302]
Hi!

I have this ad tag: 
https://ima3vpaid.appspot.com/?adTagUrl=https%3A%2F%2Fgoogleads.g.doubleclick.net%2Fpagead%2Fads%3Fclient%3Dca-video-pub-8309773808661346%26slotname%3D2055062125%26ad_type%3Dvideo_text_image_flash%26description_url%3Dhttp%253A%252F%252Fpiktv.ru%26videoad_start_delay%3D0&type=all

Sometimes the display freezes after ad:
![image](https://cloud.githubusercontent.com/assets/14952723/19946318/cfff1484-a154-11e6-8e4f-9c2d818db9a3.png)

Sometimes I get following error: 
Ad error: AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info. Caused by: Error: Error: null

How to reproduce: here https://googleads.github.io/videojs-ima/examples/advanced/

Also I've tested ad tag here http://tagvalidator.videohub.tv/. Everything was ok.

**Comment by shawnbuso** [comment]
Hey there,

That tag you're using is a VPAID adapter tag, and it's really meant for VAST implementations that don't use the IMA SDK but want IMA SDK functionality. Since the Video.js IMA plugin *does* have the IMA SDK, you should skip the VPAID adapter and use the tag that's encoded in that tag you sent me: https://googleads.g.doubleclick.net/pagead/ads?client=ca-video-pub-8309773808661346&slotname=2055062125&ad_type=video_text_image_flash&description_url=http%3A%2F%2Fpiktv.ru&videoad_start_delay=0. That's working for me.

Thanks!
Shawn

**Comment by AlexMurm** [comment]
Thank you! 
Could you advise me what is the best solution to handle tags like mine in player? It would be really cool if your plugin could handle such tags itself. 
Thanks in advance!

**Comment by shawnbuso** [comment]
These tags are specifically designed to be used in a player that does **not** have the IMA SDK implemented, so it wouldn't make sense for us to support them in our player, which does have the SDK implemented. The idea is that when you load this tag, it loads a mini IMA SDK and plays ads through that. Because we already have the full IMA SDK implemented, you don't need to use this tag. If you have more tags that point to ima3vpaid.appspot.com, you can decode the adTagUrl parameter on that tag and just use that as your ad tag.

**Comment by AlexMurm** [comment]
Thank you!
