### ISSUE TITLE
Triggering showAdControls_ and hideAdControls_ on mobile device

### ISSUE THREAD

**Issue by steevee** [googleads/videojs-ima#312]
On mobile devices is there a way to toggle ad-controls on tap or press events?

I used to run the publicly available `ima.hideAdControls_` on initiation, but since making [these private](https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L547-L565) I've had to hack it. 

It's only now I dig around I can see we're only using the `showAdControls` and `hideAdControls_` on mouse events. Do you think we should be building for at least a `touchStart` before we show the ad controls?

**Comment by shawnbuso** [comment]
I think mobile controls were hiding and showing fine when we first released this >2 years ago, but it looks like that has since changed - testing on my android device just shows the controls constantly and they're never hidden. I can look into adding touch event listeners as well, but we'll have to do it in a way that doesn't interfere with the current desktop control functionality.

**Comment by steevee** [comment]
@shawnbuso thanks for taking a look.

I was having a bit of a mind-blank as to what the ad-control behaviour should actually be, but I've just been playing with bog-standard `<video src="..." controls>` tag on an Android/Chrome device:

1. Controls display by default
    - Probably not applicable for ads, and could detract from the content, particular for ads with a short `skipoffset` 
2. Controls fade-out after ~5s
    - Suspect could be shorter for ads without being detrimental to the user experience.
3. Controls reappear on user-engagement with the video

Does that sound about right to you?
It might be a few weeks, but can take a look if you haven't got to it.

**Comment by shawnbuso** [comment]
My current plan is to just have it behave the same way as desktop, which is 2+3 in the list above. I'm a bit tied up with other things right now, though, so it will probably be a bit till I get to it as well.

**Comment by steevee** [comment]
:+1:

**Comment by shawnbuso** [comment]
FYI I've decided on a slightly different way of handling this - since IMA pauses and resume the ad on tap on mobile, I've set it up to just show the controls on ad pause and hide them on ad resume (on mobile). So when you tap the ad pauses and the controls show, and the controls stay visible until you resume the ad either by hitting the play button or by tapping the ad again.

**Comment by steevee** [comment]
@shawnbuso that feels intuitive. Thanks a bunch for taking a look!
