### ISSUE TITLE
My content video seek to 0

### ISSUE THREAD

**Issue by aydinkn** [googleads/videojs-ima#320]
Hello,

I have multiple (preroll, midroll, postroll) VAST ad tag without ad rules or VMAP. So, i listen videojs timeupdate, seeking, seeked events and call the ad (for midroll(s)).

For ad call, i am using setContentWithAdTag and it call changeSource_ function. In changeSource_ function, if player has a source already player currentTime set to 0. For this reason, when I call a midroll ads, my content video seek to 0.

```
var changeSource_ = function(contentSrc, playOnLoad) {
      // Only try to pause the player when initialised with a source already
      if (!!this.player.currentSrc()) {
        this.player.currentTime(0); // Why we do this?
        this.player.pause();
      }
      if (contentSrc) {
        this.player.src(contentSrc);
      }
      if (playOnLoad) {
        this.player.on('loadedmetadata', playContentFromZero_); // And this
      } else {
        this.player.on('loadedmetadata', seekContentToZero_); // And this
      }
    }.bind(this);
```

**Comment by shawnbuso** [comment]
Is it possible to get your ad requests in a VMAP or ad rules format? The plugin doesn't support multiple ad requests per video as-is because we already have support for that in the VMAP spec, so it would require changes to the plugin to make this work. We seek to 0 because we assume you're changing the source (because you're calling setContentWithAdTag, we expect that you're changing the content) and you'll want to play that new source from 0.

**Comment by aydinkn** [comment]
Unfortunately VMAP or ad rules not posible in my situation (Because I build a custom player like flowplayer or jwplayer). Also, IMA not supported overlay ads in VMAP.
I call setContentWithAdTag("", "midrollAdTag"). I am not send contentSrc. Because I don't want to change source but it still seek to zero.
I think changeSource_ function need to fix.

**Comment by shawnbuso** [comment]
The change source function is designed to change the source, though. Since it's an open source project, feel free to fork it and modify it as needed :)

**Comment by aydinkn** [comment]
Of course I can fork and modify but you said in code: Leave blank to use the existing content. 
```
/**
     * Changes the player source.
     * @param {?string} contentSrc The URI for the content to be played. Leave
     *     blank to use the existing content.
     * @param {?boolean} playOnLoad True to play the content once it has loaded,
     *     false to only load the content but not start playback.
     * @private
     */
    var changeSource_ = function(contentSrc, playOnLoad) {
```
Which is why I am call setContentWithAdTag with empty source.
Do you have a plan for multiple ad requests to support?

**Comment by shawnbuso** [comment]
Ok I see what you're saying, but making this change has the potential to break anyone who expects this method to seek the content to 0. I can look into an alternative way to do what you're trying to do here. Currently we don't have a plan to support multiple ad requests on a single video since this is already well supported by VMAP.
