### ISSUE TITLE
please help {URIError: URI malformed}

### ISSUE THREAD

**Issue by codex-corp** [googleads/videojs-ima#326]
Hi @shawnbuso ,
the code below is working on fine on localhost,
https://github.com/streamroot/videojs-with-ads/blob/master/prod.html

but does not work on my server , please check the below code 

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Fd (ima3.js:33)
    at Je (ima3.js:44)
    at Me (ima3.js:45)
    at Zd (ima3.js:51)
    at ae (ima3.js:35)
    at Jm (ima3.js:209)
    at new Lm (ima3.js:208)
    at Nm (ima3.js:208)
    at new Ko (ima3.js:244)
```

**Comment by shawnbuso** [comment]
Hey there,

What ad tag are you using? It looks like there's a problem either with your tag or with a URL in the response that tag is returning.

Thanks,
Shawn

**Comment by codex-corp** [comment]
i found the problem but i cannot fix it ,
the problem because the page uri includes query string , did you saw this problem before?

**Comment by shawnbuso** [comment]
The SDK should be able to handle this as long as the query string is properly formatted - do you have the page hosted somewhere so I can reproduce the issue?

**Comment by codex-corp** [comment]
yes check here please ,
http://player.mangomolo.com/v1?id=NzE=&channelid=Ng==&countries=Q0M=&w=100%&h=100%&filter=DENY&signature=8c8e219c9b02496f2b9ef78c5461f4c6

**Comment by shawnbuso** [comment]
OK it looks like the issue is the "%" in your URL. Those are a special character for the URL standard so they need to be encoded as "%25". So your new URL looks like this:

http://player.mangomolo.com/v1?id=NzE=&channelid=Ng==&countries=Q0M=&w=100%25&h=100%25&filter=DENY&signature=8c8e219c9b02496f2b9ef78c5461f4c6

I'm still not seeing ads with that URL, but I'm not seeing the IMA error either. Could you tell me where your page is loading the player implementation from so I can put in some breakpoints to debug?

**Comment by codex-corp** [comment]
thanks @shawnbuso , the problem is fixed now .
now i have problem with ads if player has aspect ratio = 16:9, i can hear the ad but the screen is black.

**Comment by codex-corp** [comment]
@shawnbuso can you check the player below ?
http://player.mangomolo.com/v1?id=NzE=&channelid=Ng==&countries=Q0M=&filter=DENY&signature=8c8e219c9b02496f2b9ef78c5461f4c6
