### ISSUE TITLE
Using AdRules > Midrolls don't play in iOS

### ISSUE THREAD

**Issue by BenErdos** [googleads/videojs-ima#328]
We have VideoJS implemented here:

http://qa-m.sport5.co.il/articles.aspx?FolderID=378&docID=146627&lang=He

Using the below AdCall:

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/423905808/Sport5&ciu_szs&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar=premidpostpod&deployment=gmf-js&cmsid=496&vid=short_onecue&correlator=3775340396490042&ad_rule=1&sdkv=h.3.156.0&sdki=3c09&scor=294187626513507&adk=2588068644&osd=2&frm=1&sdr=1&mpt=videojs-ima&mpv=0.2.0&url=http://qa-m.sport5.co.il/articles.aspx?FolderID=378&docID=146627&lang=He&ged=ve4_td20_tt2_pd20_la20000_er499.0.499.0_vi400.0.880.320_vp0_eb16619

Which returns an AdRule (VMAP) however in iOS, the midrolls don't play consistently.

Is anyone else experiencing this issue?

**Comment by shawnbuso** [comment]
Could you elaborate on what you mean by mid-rolls not playing consistently? Are you seeing errors or ads freezing? Or does the playback just skip the ad altogether and carry on playing content? If the latter, it could be that your ad request is hitting a frequency cap and not returning an ad, so when it's time to play an ad you get nothing back from the ad server. You can get more info about what's going on by loading ima3_debug.js instead of ima3.js on your test page.

**Comment by yaakovbg** [comment]
Hi I Have added the ima3_debug.js on the above(http://qa-m.sport5.co.il/articles.aspx?FolderID=378&docID=146627&lang=He).
Seems that the ad doesnt even run in time ,

In the following link http://player.sport5.co.il/VidClean/sportsvid/testiframe.html?v=3 there are 2 iframes one is the article hidden and the second the simple example of the ima(https://googleads.github.io/videojs-ima/examples/simple/).
Seems that even on the example the problem is reproduced the simple example once its sitting on the same link with the article.

**Comment by shawnbuso** [comment]
I'm not able to reproduce the issue on my end - I'm seeing mid-rolls play fine. Would you be able to share the console log from the browser when you see the issue? If your page is loading a lot of resources it could be that your ad request is timing out because other resources are getting in the way.

**Comment by yaakovbg** [comment]
I have created a page from your iphone example with our adtag and with ima3_debug.js:
http://player.sport5.co.il/vidclean/adstest/?v=10
Which seems to run fine.
Furthermore I have created a link with 2 iframes with the above link and with the article hidden,:
http://player.sport5.co.il/vidclean/adstest/?v=10.
And again once the page holds the article the midrolls dont run.
The vmap response seems fine:
![image](https://cloud.githubusercontent.com/assets/11254069/22860912/d780aac4-f113-11e6-886a-3b92eb41751d.png)

and the console seems to show a jump from the preroll to the postroll:
![image](https://cloud.githubusercontent.com/assets/11254069/22860901/91c584d2-f113-11e6-8e29-27e7b907d3dc.png)

Hope I was clear enough.

**Comment by shawnbuso** [comment]
It looks like those 2 links are the same, and mid-rolls are working for me on that page :/ I think you need to send the second link again. 

I'm not sure what your page structure is like, but make sure that the ad display container created by the plugin isn't being hidden by your page manipulations - if the SDK tries to play an ad but the container is hidden, it will abandon the ad.

**Comment by yaakovbg** [comment]
Oops sorry,
the other link is:
http://player.sport5.co.il/vidclean/adstest/testiframe5.html?v=2.
In this page there are two iframes one  of the article hidden, and the second the ihpone example with our ad tag. 
As I said on ios the midrolls dont run, but  on the link above(http://player.sport5.co.il/vidclean/adstest/?v=10) - they do work.

**Comment by shawnbuso** [comment]
Hey there,

Sorry for the delayed response - I took a look at your pages but now all the ad break requests are returning empty VAST (for either page). Are you still able to repro?

Thanks,
Shawn

**Comment by yaakovbg** [comment]
Hi sorry for my delay,
Strange  I seem to get a response:
![image](https://cloud.githubusercontent.com/assets/11254069/24079200/2c0b2500-0c8b-11e7-9758-a48c39409a80.png)
 Can you check again?

**Comment by shawnbuso** [comment]
I'm seeing your initial VMAP request return fine, but the ads in that repsonse (https://pubads.g.doubleclick.net/gampad/ads?slotname=...) are all returning empty.
