### ISSUE TITLE
Error on iPhone (TypeError: undefined is not an object (evaluating 'd.clientX'))

### ISSUE THREAD

**Issue by tonykor** [googleads/videojs-ima#348]
I'm getting this error on iphone, sometimes player not react on touching, and video not starting to play:

I — client.js:8:425TypeError: undefined is not an object (evaluating 'd.clientX')

**Comment by shawnbuso** [comment]
Is this on an actual device or on a desktop browser emulating an iPhone? We've seen this on the latter, but not yet on the former. If on an actual device, can you share the device type and version? Thanks!

**Comment by tonykor** [comment]
it's on actual device MD298KN/A (iphone 5), iOS version 10.2.1 (14D27)

**Comment by s3bubble** [comment]
We are also experiencing this issue on iPhone you can test on the main video on our homepage.

https://s3bubble.com/

Sometimes it will work sometimes it will not, I think it's down to whether the ad loads correctly or not or might be a https issue not sure.

Thanks

**Comment by samueleastdev** [comment]
Hi @shawnbuso 

Any updates on this?

We are experiencing issues on mobile i have moved the test to here.
http://streamiumtheme.com/action/beauty-the-beast-trailer/

It play fine through the desktop no issues works great but it you open the url on iPhone i am testing on a 6 the it just hangs and the video doesn't start.

If i test with chrome with iphone selected in devs tools i get this error and it skips.
~~~
"The media could not be loaded, either because the server or network failed or because the format is not supported."
~~~

I have setup a test suite here:
https://s3bubble.com/advert-tester/

The url i am using is.
~~~
https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on
~~~

Thanks 

Sam

**Comment by shawnbuso** [comment]
@samueleastdev are you still seeing your issue? I loaded up your test page on desktop but I'm not seeing an ad, so maybe the serving expired?

**Comment by ypavlotsky** [comment]
Closing this issue. If you're still seeing it, please let me know.
