### ISSUE TITLE
Why does this library alter the main videojs player's source?

### ISSUE THREAD

**Issue by joshuairl** [googleads/videojs-ima#368]
If the Ads are playing in some floating iframe anyway, why should this plugin EVER concern itself with the source of the video player?

Just trying to understand it better.

I'm really struggling to make use of it at all.
I have an app I'm writing that needs to continuously play video back to back.  It doesn't appear this plugin was designed for this.

When I try to do manual ad breaks the plugin doesn't work anymore.

Can anyoen tell me which version of video.js, videojs-contrib-ads, is most compatible?
Sadly, I'm also needing videojs-contrib-hls which requires a certain version of video.js of like 5.10+ i think. :-/

**Comment by shawnbuso** [comment]
Hey Josh,

We handle the video source because the IMA plugin needs to know when the source changes in order to work properly. The way we make sure we know when this happens is by forcing you to do it through us. You should be able to modify our playlist example to do what you want though - simply listen for the video to finish via `addContentAndAdsEndedListener`, and use the code in the playlist example's onPlaylistItemClick to play your next video. Let me know if there's anything else I can do to help out.

Thanks!
Shawn

**Comment by shawnbuso** [comment]
Closing but feel free to re-open if you have any more questions :)
