### ISSUE TITLE
Update to latest videojs-contrib-ads

### ISSUE THREAD

**Issue by shawnbuso** [googleads/videojs-ima#383]
As of this filing we're on 3.1.2 and they've released 4.2.8.

This should also lead to a resolution of #167

**Comment by dasanra** [comment]
It will also be wonderful if video.js dependency is updated or at least changed from ```~5.3``` to ```^5.3``` and let us decide wich version of video.js to use.

For now I´m able to use ```videojs-ima 0.6.0``` with ```video.js 5.20.1``` without issues (tested in Chrome, Firefox, Edge, iOS, Android) but I had a hard workaround using Yarn + Webpack because videojs-ima was always being init in a ```video.js 5.3```instance (because dependency range says it can´t work with ```>5.3.X```)

**Comment by shawnbuso** [comment]
Our plugin is pretty complex, so we like to test it with every new 5.X version that comes out before we say we can support it. For this reason we'll leave the config as ~5.X, but feel free to try out newer versions in your implementation to see if they work (though we can't guarantee that they should until we update the package.json file).

**Comment by denisvlr** [comment]
hello @shawnbuso I suggested a PR to update to videojs-contrib-ads 5.0.3: https://github.com/googleads/videojs-ima/pull/405
Based on review of their changelog, migration guides for 4.X and 5.X and manual testing, it seems we just need to add a `ads-ad-started` event.

Can you think of something else that needs to be checked or should be changed?

**Comment by shawnbuso** [comment]
I think that's about it - I took a look at the PR and it looks like you just need to sign our CLA and we can merge the change. Thanks!
