### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by jonigl** [googleads/videojs-ima#394]
Hi, 

I have been using your plugin for a while and I am having an error in the console when start to load an ad (my add tag is a vmap) :

`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

This error is happening randomly. Any ideas of what could be happening?

Thanks in advance.

**Comment by shawnbuso** [comment]
We see this on our end as well and we're looking into it. So far it has not affected ad playback, but if you see it start to cause playback errors definitely let us know.

**Comment by KevinBrogan** [comment]
Is it a programmatic vpaid ad tag? I only see this from poorly programmed programmatic ads that screw up their event listening logic.

**Comment by shawnbuso** [comment]
We're seeing this for a wide range of ads, video and VPAID. If it's affecting your ad playback definitely let us know - right now we don't see it breaking anything, just logging to the console.

**Comment by dcalhoun** [comment]
@shawnbuso I believe this promise rejection is impacting my usage. I am unable to rely on the fulfillment of [`HTMLMediaElement.play()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) whenever the video has an ad.

For example, I attempt to autoplay the video and handle a rejection by the browser (e.g. Safari 11 disallows it).

```javascript
const player = window.bc(/* Brightcove config */);
player.ima(/* IMA config */);

player.ready(() => {
  player.on('loadedmetadata', () => {
    const playPromise = player.play();

    if (playPromise) {
      playPromise.catch(() => {
        // render friendly UI to allow user to begin playback
      });
    }
  });
});
```

Currently, the play promise rejects, but in reality playback was successful. That puts me in an odd place not knowing whether playback was actually successful. The end result being I render unnecessary UI because the video is in fact successfully playing.

In this specific case, I'm using a [Brightcove](https://www.brightcove.com) player and their IMA support. It's possible this is purely a bug in my or Brightcove's source, but I came across this issue and it describes exactly what I'm experiencing.

**Comment by shawnbuso** [comment]
Thanks for the info - in this case I think you would want to go to brightcove for troubleshooting since they wrote the IMA integration. Your use of the promise is also unfamiliar to me though - in the past I've used them as follows:

    player.play().then(successFunction, failureFunction)

Is your code a new way of handling promises, or just a different but also valid way?

**Comment by dcalhoun** [comment]
Yes, [`Promise.prototype.catch()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) is merely an alternative format. I'll definitely inquire with Brightcove support as well.
