### ISSUE TITLE
Access ad information before playing video

### ISSUE THREAD

**Issue by bcharna** [googleads/videojs-ima#406]
Hey ya'll. I originally posted about this issue in the IMA SDK forum, but the underlying issue actually ends up being within this plugin. Here is the link to the forum post for reference: https://groups.google.com/forum/#!topic/ima-sdk/6t1FrnSK8jM.

Long story short, we want to be able to access ad information (i.e. creative id, ad system, etc). The `google.ima.AdEvent.Type.LOADED` event is not fired right away after `videojsPlayer.ima.requestAds()` is called. Rather, the player must be triggered to play via `videojsPlayer.play()` first, and then the LOADED event is fired, even though the ad is loaded right away, before play is triggered.

I have found a workaround:

```
videojsPlayer.ima.requestAds()
videojsPlayer.ima.adsLoader.addEventListener(google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED, =>
  # calling this init function below rather than waiting for ima.startFromReadyCallback() to call it
  # allows us to receive the LOADED event right away. it does mean that LOADED will be triggered a
  # second time once play is triggered, but we can just ignore that firing of the event.
  videojsPlayer.ima.adsManager.init(
    videojsPlayer.ima.getPlayerWidth(),
    videojsPlayer.ima.getPlayerHeight(),
    google.ima.ViewMode.NORMAL
  )
  videojsPlayer.ima.addEventListener(google.ima.AdEvent.Type.LOADED, (e) =>
    adData = e.getAdData()
    # do stuff here
  )
)
```

Any chance the plugin can be modified so that the LOADED event is triggered upon requesting the ad without this hack? Thank you!

**Comment by shawnbuso** [comment]
Hey there,

The LOADED event is fired when each individual ad is loaded. I think we should be able to make this work when we get preloading working, but currently that loaded event will only fire in the seconds before the ad plays when the SDK starts buffering it.

**Comment by bcharna** [comment]
👍 the workaround will suffice for now, but thought I'd throw this out there as other people may want to do something similar to us. Thanks!

**Comment by shawnbuso** [comment]
Ah ok, it looks like you're seeing the same issue as #353 - we're having issues with the play button being disabled when preload is used. That user posted a workaround in that thread which involves waiting until the user clicks play to play ads. The issue is that the ad container is rendering above the play button and stealing its clicks. You can also try removing the z-index parameter from the ad container's stylesheet until the ad starts, and then re-adding it when the ad is playing.

As for the second issue, it looks like you have a different version of the Video.js stylesheet than we're using here. The one we use defines a font family called VideoJS, which is where we get the UI icons from. Your CSS seems to be missing that. Could you try using [this stylesheet instead](https://github.com/googleads/videojs-ima/blob/master/examples/simple/index.html#L20) to see if that works?

**Comment by shawnbuso** [comment]
Sorry, deleted my previous comment - that was meant to be a response to a different issue :)

**Comment by shawnbuso** [comment]
Good news! It looks like you can do this already with a combination of preloading and using a custom adsManagerLoadedEvent listener. I modified the simple sample to demonstrate how - take a look [here](https://codepen.io/imasdk/pen/goJKQQ). Let me know if you have any questions!

**Comment by shawnbuso** [comment]
Hey there, does this give you what you need? If so I can close out this issue. If not we can look for another solution. Thanks!

**Comment by bcharna** [comment]
Hey Shawn, I’m no longer working on this project :). Thanks for the follow up, I think it’s safe to close this out.
