### ISSUE TITLE
Inline ad isn't visible in fullscreen on iPad iOS 10 when using fullscreen button

### ISSUE THREAD

**Issue by marguinbc** [googleads/videojs-ima#411]
#Hi team,

I've been troubleshooting an issue with iOS 10 on iPads where if the video player has `autoplay`, `muted`, `playsinline` it begins playing inline but the ad is not visible when switching to fullscreen.

I can reproduce with this example of the videojs-ima3 plugin:

https://googleads.github.io/videojs-ima/examples/autoplay/

**Steps to reproduce:**

1. Open page on an iPad with iOS 10
2. Watch that ad autoplays muted inline
3. Tap the fullscreen button

**Expected behavior**: Ad continues playing while in fullscreen and when returning to inline from fullscreen

**Actual behavior:**  Ad is not visible in fullscreen but you can hear the audio - instead of seeing the ad in fullscreen, you see the paused content video (or poster if there is one)

Calling `videojs.players.content_video.ima.adsManager.isCustomPlaybackUsed() `in the console yields false which seems odd because I thought iPad was always supposed to use custom playback to support inline play, overlays, etc. and even using `setDisableCustomPlaybackForIOS10Plus(false)` wouldn't override custom playback.

Can you guys take a look and see if you also see that custom playback is disabled and determine if this is a bug in the plugin or the IMA SDK?

Thanks in advance

**Comment by shawnbuso** [comment]
Does this work if you remove the playsinline attribute from the video element? It shouldn't change the behavior, since playsinline is the default for iPad.

**Comment by marguinbc** [comment]
@shawnbuso, it does work if I remove playsinline however, since the same video element may be viewed on iPads, iPhones, Androids, etc. the ad and content video will no longer play inline.  I also filed a support ticket with the IMA SDK support team and they confirmed this appears to be a bug in the SDK and are looking into it further.

**Comment by shawnbuso** [comment]
Thanks for the update - since we're also looking into this on the IMA SDK side I'll mark this as an IMA issue and look for updates there.

**Comment by sgromkov** [comment]
I have the same problem. Will wait for update.

**Comment by mimse** [comment]
Same here @marguinbc do you have a link to the support ticket?

**Comment by marguinbc** [comment]
@mimse, I filed it via email through our IMA SDK contacts and don't have a link or tracking number.  The last response received indicated using playsinline on an iPad is not a supported configuration for the IMA SDK.

> Our team has determined that this behavior is working as intended. The playsinline attribute should not be used with the IMA SDK on iPad because the iPad will play inline by default.

**Comment by shawnbuso** [comment]
I did some investigating and I have a breakdown of the issue.

We basically have to fullscreen modes with the IMA SDK.
Option 1: Make the content player fullscreen. This only works when we re-use the content player for ads, which we only do on select platforms (iPad is one of those platforms).
Option 2: "Fake fullscreen." Make the browser window fullscreen (remove the address bar and other chrome), then resize the video player and ad container to take up the entire browser window. This is our preferred method, and how we do it on all platforms where we have separate players for content and ads (Android, desktop web, etc.)

On iPad we employ option 1, because we re-use the content player for ads. *However*, when you specify `playsinline`, we use a separate player for ads instead of re-using the content player. When you hit the fullscreen button, we make the content player fullscreen, but the ads keep playing in their own player in the backgorund.

We can't use fullscreen option 1 on iPad because iPad doesn't let you programmatically enter fullscreen with the browser window - it will only let you put specific elements into fullscreen mode. That won't work for us because we need to put both the content player and ad container into fullscreen mode. For the time being, the only good option is to refrain from using `playsinline` on iPad so the IMA SDK continues to re-use the content player for ads.
