### ISSUE TITLE
Videojs ima Flash VPAID ads

### ISSUE THREAD

**Issue by adnanmokhtar** [googleads/videojs-ima#412]
i use  the option 'vpaidMode: google.ima.ImaSdkSettings.VpaidMode.INSECURE' to play flash ads.

it works fine with some tags here:
http://platform.n-stream.tv/ads/freewheel/meetrics_vpaid_flash/16118
http://platform.n-stream.tv/ads/freewheel/google_active_view_vpaid_flash_and_js/16118

other tags return an error:
http://platform.n-stream.tv/ads/freewheel/adloox_flash_vpaid_js/16118
http://platform.n-stream.tv/ads/freewheel/crea_enrichie_massmotion_flash_vpaid_js/16118

the error is:
Ad error: AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info. Caused by: Error: Error: No Ad found.

why these tags get that error
http://ads.stickyadstv.com/vast/vpaid-adapter/1868025
http://ads.stickyadstv.com/vast/vpaid-adapter/1868041

what is the solution?

**Comment by shawnbuso** [comment]
The IMA SDK actually dropped support for Flash VPAIDs a short time ago - http://googleadsdeveloper.blogspot.com.au/2017/01/deprecating-flash-in-ima-sdks.html - so Flash VPAIDs are not expected to work.

**Comment by shawnbuso** [comment]
Sorry about that, I responded prematurely - it looks like you have both JS and Flash VPAIDs being returned. The JS VPAID is failing because it's making a second ad request of its own, and that request is returning empty VAST - http://ads.stickyadstv.com/www/delivery/swfIndex.php?zoneId=1868025&vav=9617581661d40b18597c30ee549f1789&vaviv=09efb31ddb37a135e775b4f1e0d50389&reqType=AdsSetup&protocolVersion=2.0&mustangVersion=1.7.16.2&componentId=vpaid-adapter&loc=http%3A%2F%2Fimasdk.googleapis.com%2Fjs%2Fcore%2Fbridge3.177.1_en.html&videoSlotCanAutoPlay=true&playerSize=640x360&supportsFlash=false&supportsJavascript=true. You'll want to take a look at the ad serving set up there to see why you're not getting an ad back.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need help feel free to re-open. Thanks!
