### ISSUE TITLE
postroll with hls cause issue

### ISSUE THREAD

**Issue by shaolintibo** [googleads/videojs-ima#437]
when we configure one postroll with an hls stream, the postroll is well played; and when the postroll is finished; one error appears. so we can't replay video. if we disable ima plugin we can replay the video when is ended

error:
_VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}_

here a sample to reproduce:
https://codepen.io/shaolintibo/pen/dVBPLZ

do you have an idea where do the problem come from ?

**Comment by shaolintibo** [comment]
after some tests, 
I confirm that modifications made on this branch seems solves this issue

thanks a lot

**Comment by Jerome-lara** [comment]
Hi @shaolintibo ,
I encountered a problem. The official demo was changed from mp4 to m3u8 video. On some specific devices such as iPhone user agent, the video could not be played after the pre-roll ads, and error code: 4(The media could not be loaded, either because the server or network failed or because the format is not supported) was prompted.

Can I have a look at your demo?
