### ISSUE TITLE
Ads are no longer playing on Desktop (Chrome, Safari)

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#440]
As of about 30 minutes ago, every ad request I've seen now results in a 1009 error.  We have not made any updates to our player code in several days.

This video has a direct test ad, so fill should be 100%:
https://dev.player.dotstudiopro.com/share/57be8615d66da81809a33855?targetelm=.player&companykey=57bdf792d66da8b744a33855&autostart=true&debug=true

The console log is a bit messy, but I do log out ad errors and you'll see the 1009 errors.  This had ads when I was last testing with it some 45 minutes to an hour ago.

The following VMAP tag is called for ads: https://api.dev.myspotlight.tv/vmap/57be8615d66da81809a33855/833/469/57be8615d66da81809a33855/https%3A%2F%2Fdev.player.dotstudiopro.com%2Fshare%2F57be8615d66da81809a33855%3Ftargetelm%3D.player%26companykey%3D57bdf792d66da8b744a33855%26autostart%3Dtrue%26debug%3Dtrue

Which then leads to our ad server, which delivers the Toyota ad.  PLEASE NOTE: I cannot reproduce this in the `Video Suite Inspector`.

Package Versions:

    `"video.js": "5.19.1",`
    `"videojs-contrib-ads": "^5.0.3",`
    `"videojs-contrib-hls": "5.10.1",`
    `"videojs-ima": "^0.5.0"`

**Comment by shawnbuso** [comment]
We haven't made any changes on our end today - the most recent IMA SDK change was back on 10/20, and the videojs-ima plugin doesn't have an auto-update feature so that code won't change without you changing it. If I check the console log I do see an ad error coming from videojs_hls_ads_desktop_core.js saying that the response didn't contain any valid ads, but that same response plays fine on our[ video.js test player](http://googleads.github.io/videojs-ima/examples/advanced/) and in our [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector). (The VSI doesn't use the videojs-ima plugin, but it is using the IMA SDK.) Are you setting any mimeTypes in your adsRenderingSettings? I see that the response only has one mime type and it's an mp4, so if you're changing the mimetypes and disallowing mp4 that could be causing an issue. Could you load ima3_debug.js on that test page so we can see a higher level of logging? Thanks!

**Comment by marguinbc** [comment]
Hi Sean,  It looks like the IMA SDK appears to have been updated to version 3.183.1, but the most recent version listed on the [release notes page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history) and the ima-sdk forum is 3.182.1

**Comment by stoicbuddha** [comment]
Yeah, I checked the revision history earlier in case that was it, but no dice.

I am not setting any mimetypes.  Here are the options I use when I set up the ads:
`var options = {
    id: typeof opts.targetelem !== "undefined" ? opts.targetelm : 'dsp-vid-js-player',
    adTagUrl: adTag,
    numRedirects: 8,
    vpaidMode: 'INSECURE'
};`

**Comment by marguinbc** [comment]
If you do google.ima.VERSION in the console it will show the current version... which is ahead of what is listed

**Comment by stoicbuddha** [comment]
So...they did an update and didn't document it?  That seems like it could cause some issues.

**Comment by shawnbuso** [comment]
It looks like we did have a release earlier this afternoon and we're in the process of updating the release notes now. Are you working on that test page currently? I'm trying to test again but I'm getting "videojs-ima-ad-events.js?bust=1509050606572:645 Uncaught TypeError: Cannot read property 'plugin' of undefined" before it makes the ad request.

**Comment by stoicbuddha** [comment]
Hey Shawn, I'm pushing an update right now; it's an unrelated issue. Check in about 2 minutes.  The ima debug script should be pulled now on that video.

**Comment by shawnbuso** [comment]
Thanks for the update. I'm still looking into this - at this point it looks like it's isolated to your page. I'm working with the IMA SDK eng team now to see what may have caused this.

**Comment by shawnbuso** [comment]
Taking a look at the page again, it looks like it's now pulling down ima3.js and ima3_debug.js. Could you remove the call that loads ima3.js? Sorry if my initial instructions were unclear. Thanks!

**Comment by stoicbuddha** [comment]
This is affecting our live player on client sites as well.  It may be isolated to our player but it's not isolated to that page.

**Comment by stoicbuddha** [comment]
Hey Shawn, I just noticed it's pulling both; pushing a fix now.

**Comment by shawnbuso** [comment]
Thanks for the fix - I'm talking to the team about rolling back today's release to get you back on 3.182.1. Would it be possible to create a static copy of that test page for us so we can continue to test for the next few days? We're still not sure what's causing the error, so we want to make sure we get that nailed down so our next release doesn't break you again.

**Comment by stoicbuddha** [comment]
You should be able to just use that page.  We have periodic dev updates to that player, but you're free to use that page to debug as much as necessary.  

When they do roll back, will you let us know, so we can notify our clients?

**Comment by shawnbuso** [comment]
Thanks for the info - we initiated the roll back now. You should see 3.182.1 being loaded in the next 5-15 minutes (as caches clear).

**Comment by stoicbuddha** [comment]
Hey Shawn, looks like ads are working for me again on desktop.  Thanks for the quick and thorough response.  As mentioned, use that page as much as you need for debug and feel free to let me know if you need anything.

**Comment by shawnbuso** [comment]
I'm seeing them working on my end as well now, thanks! We'll take a look at that test page to figure out what went wrong and make sure it's fixed before the next release.

**Comment by stoicbuddha** [comment]
Is there a way to subscribe somewhere to get notified when there is an update, or are planning an update, etc?

**Comment by shawnbuso** [comment]
We do have a [thread](https://groups.google.com/forum/?hl=en_US&fromgroups=#!topic/ima-sdk/tm1DMEMA758%5B1-25%5D) on the IMA SDK support forum that gets updated with new releases. This one hasn't made it there yet, though. We have them updated within 24 hours.

**Comment by stoicbuddha** [comment]
Awesome, thank you!  I just subscribed to it. I don't suppose there is any way to know beforehand?

**Comment by shawnbuso** [comment]
Not currently - our release dates aren't set in stone because we have a [canary process](https://martinfowler.com/bliki/CanaryRelease.html) to make sure things don't break before we release. If the canary shows that something is going wrong, we abandon the release, or cherrypick a fix if we know the issue, or potentially take other action to delay the release.. In this case our canary process didn't catch the breakage because it was only affecting your implementation, so it didn't create enough of a signal to make it through the noise.
