### ISSUE TITLE
How to control ad playback

### ISSUE THREAD

**Issue by marcoliceti** [googleads/videojs-ima#474]
While the user can pause / unpause the ad, change volume, etc., I don't understand if it's possible (and how) to do the same **programmatically**.

Say `player` is my `videojs` instance, e.g.:

```js
var player = videojs('myVideoElementId', myOptions);
player.ima(myImaOptions);
```

I thought that calling `player.pause()` or `player.volume(x)` during the ad would do, but it's not working.

**Note:** I need this in order to implement unmute on mouse over.

**Comment by canhnm** [comment]
For controlling ad volume, you have to use adsmanager from ima, not player volume:
player.ima.adsManager.setVolume(adsvol);
Advol is from 0 to 1. Eg, player.ima.adsManager.setVolume(0.5); means ad volume will be 50%.

Hope this help!

**Comment by marcoliceti** [comment]
Hi, `player.ima.`**`getAdsManager()`**`.setVolume(x)` did the trick!

Thanks!

**Comment by shawnbuso** [comment]
Thanks for the help, @canhnm! @marcoliceti you can control other aspects of the ad via the AdsManager as well - see https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsManager. Note that some of them will cause issues if called directly, though, instead of through the plugin.
