### ISSUE TITLE
Fullslot ads in videojs

### ISSUE THREAD

**Issue by Skychko** [googleads/videojs-ima#476]
I'm trying to run FullSlot ads in videojs player.
But they don't work for me.
Does videojs-ima maintain FullSlot ads?
Custom tag: https://skychko.com/fullslot/vast.xml
It works here: 
- https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector
- (jwplayer): https://developer.jwplayer.com/tools/ad-tester/
but doesn't work with videojs, i.e here: 
- https://googleads.github.io/videojs-ima/examples/advanced/
- https://skychko.com/fullslot/index.html

Param 'forceNonLinearFullSlot' doesn't help as well.

It's possible to see an error on console:
videojs.ima.js:1478 AdsLoader error: AdError 503: Non linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.

**Comment by shawnbuso** [comment]
Thanks for the info - I'm not sure why this is working in the Video Suite Inspector but not in the Video.js plugin. I'm working with the IMA team now to try to determine the cause. I'll let you know when I have more info from them.

**Comment by PaulAnnekov** [comment]
I will explain why we have this issue.

# General
- https://skychko.com/fullslot/vast.xml has 1 nonlinear image ad of size 336x280.
- *vastinspector*/*jwplayer*/skychko.com/*videojs-ima* player sizes are all 640x360

# Players behavior
## https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector
- sets nonLinearAdSlotWidth and nonLinearAdSlotHeight to the same values as for linear ones - 640x360 (check screenshot attached)
- shows this ad as linear (=fullslot)
![google_nonlinear_size_hack](https://user-images.githubusercontent.com/1203892/35625793-39d82fd2-069c-11e8-9f77-115e37fa5abd.jpg)

## https://developer.jwplayer.com/tools/ad-tester/
- sets nonLinearAdSlotWidth to player width and nonLinearAdSlotHeight to (player height - controlbar height), so we get - 640x324 (check screenshot attached)
- shows this ad as linear
![jwplayer_nonlinear_size_hack](https://user-images.githubusercontent.com/1203892/35625794-3a107310-069c-11e8-81c2-6f60e1b77d7d.jpg)

## https://googleads.github.io/videojs-ima/examples/advanced/
- sets nonLinearAdSlotWidth to player width and nonLinearAdSlotHeight to (player height/3) (looks like it's recommended by ima sdk behavior https://developers.google.com/interactive-media-ads/docs/sdks/html5/#requestads) - 640x120 (https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L221).
- ima sdk throws an error `videojs.ima.js:1478 AdsLoader error: AdError 503: Non linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.`

## https://skychko.com/fullslot/index.html
- the same as above
- sets `forceNonLinearFullSlot: true`

# IMA SDK behavior
- if nonlinear ad doesn't fit in nonlinear slot dimensions - it won't be shown
- it looks like ima sdk compares player size and nonlinear ad image size. If it's too big to be shown as nonlinear (=ad overlaps all main video content), it transforms it to linear (`getAd().isLinear()==true`) and shows accordingly
- according to what we see for players above, it looks like IMA SDK first compares slot size and ad size from xml. If it doesn't fit, ima throws an error and totally ignores `forceNonLinearFullSlot` flag. We think `forceNonLinearFullSlot` says "*We don't care xml wants us to display nonlinear ads, display them as linear ones!*", but it's not, it still compares dimensions of nonlinear slot and nonlinear ad from xml.

# Solution
I think videojs-ima should behave like *vastinspector* and *jwplayer*. But I think it's useless to subtract control bar height (like *jwplayer* does) because nonlinear ad will be transformed to linear if it's too big, so it will never overlap control bar. I can make a PR, if vjs-ima devs agree with me.

**Comment by shawnbuso** [comment]
Thanks for the thorough investigation! In the short term I think it's fine to change the plugin's nonLinearAdSlotHeight so that this works. In the long-term I'll work with the IMA team to see if we can get these full slot ads treated as linear ads instead of non-linear ads.

**Comment by dhruv2204** [comment]
Hey

Thanks for this insight. What would be the case if the device size is very small say a screen of 320x240, where innerwidth reduces even more due to browser address bar?

The non-linear image asset is so big and not converted into a linear asset. Every time a 503 error will be thrown. Cannot even make it work by setting nonLinearAdSlotHeight then.

Thanks
