### ISSUE TITLE
autoplay the playlist?

### ISSUE THREAD

**Issue by Sudhakar-Sukumar** [googleads/videojs-ima#493]
Hi

How can we autoplay the video. once  first video completed how shall we make autoplay the next vidoe for the below demo video?
https://googleads.github.io/videojs-ima/examples/playlist/

kindly help us to resolve this issue.

**Comment by ypavlotsky** [comment]
Hi,

The code to make this happen is pretty straightforward, but I ran into an issue with either the player or contrib-ads, so I opened an issue with (them)[https://github.com/videojs/videojs-contrib-ads/issues/324].

**Comment by ypavlotsky** [comment]
Here's a way to do this in the playlist sample. You'd add this to the code right after `this.player.ima(this.options)`:

`this.player.ima.addContentAndAdsEndedListener( () => {
    this.player.ima.setContentWithAdTag(
        this.contents[1],
        null,
        false);
    this.player.poster(this.posters[event.target.id]);
    this.player.ima.requestAds();
    this.playlistItemClicked = true;
  });`

This waits for content and ads to finish playing, then transitions to the second video in the playlist. Note that `playlistItemClicked` is set to true just so that the player plays automatically after loading. You'd naturally rename this to something else in your implementation.
