### ISSUE TITLE
ima overflows out of player's bounds

### ISSUE THREAD

**Issue by mysuf** [googleads/videojs-ima#505]
I faced issue related to bounds of videojs player. videojs-ima overlayer overflows player's top bound.

**How to reproduce this issue:**
Put two players in column without any gap. Bottom will block control bar of the top player by overlayer of bottom player.

**How to fix this issue:**
You should either use variable height of this overlayer like .`vjs-text-track-display` does or if you need preserve fixed height, apply `overflow: hidden` to entire player like `.video-js { overflow: hidden }`

_Note: this issue was first mentioned in #492_

**Comment by ypavlotsky** [comment]
Hi there,

I am not seeing the issue when I put two players in a page. Do you have a sample page for the issue?

**Comment by mysuf** [comment]
Ah. I did not mentioned that it happens only when non-linear ad is used. You use negative margin-top overlayer(.bumpable-ima-ad-container or so) for this ad type. This negative margin overflows top bound and overlaps controls of top player. Pause bottom player when non-linear is active and try to control top one..

**Comment by ypavlotsky** [comment]
Thanks for the details, I was able to repro the issue.

**Comment by ypavlotsky** [comment]
We don't want to modify the video.js stylesheet, because there's nothing preventing the player from programmatically undoing our modifications. Instead, you should modify the CSS on your video player that you pass into the video.js player to have `overflow:hidden`. For example, in our [examples](https://github.com/googleads/videojs-ima/blob/master/examples/style.css), I added a rule that sets that on `#content_video`.

**Comment by mysuf** [comment]
Yea. It makes sense. I guess that you have reason to force fixed height on non-linear and use negative margin. I already fixed it but also reported as possible issue. Feel free to close it. Thanks.
