### ISSUE TITLE
Is it possible to init ima in html?

### ISSUE THREAD

**Issue by Kogoruhn** [googleads/videojs-ima#509]
Hi! Is it possible to init ima (like other plugins) in html like this?
```

<script type="text/javascript">

    var player = videojs(playerID, {
        "sources": [{
            "src": "http://#",
            "type": "application/x-mpegURL"
        }],
        "plugins": {
            "ima": {
                "id": playerID,
                "adTagUrl": "https://#"
            }
        }
    });
</script>
```
Now im stuck on an error:

> Cannot read property 'el' of undefined
>     at PlayerWrapper.injectAdContainerDiv (bundle.js:103278)
>     at Controller.injectAdContainerDiv (bundle.js:104817)
>     at AdUi.createAdContainer (bundle.js:103641)
>     at new AdUi (bundle.js:103628)

...arising from this line:

`this.vjsControls = this.vjsPlayer.getChild('controlBar');`
But controlBar not exist yet.

Any tips?

**Comment by shawnbuso** [comment]
It should work fine as long as you load the other dependencies and initialize the video.js player first. For example, if you take our [simple example](https://github.com/googleads/videojs-ima/tree/master/examples/simple) and place all of the code in ads.js in a script tag instead of loading the file it works fine. Replace this:

`<script src="ads.js"></script>`

With this:

```
<script type="text/javascript">
  (contents of ads.js)
</script>
```

**Comment by Kogoruhn** [comment]
Thanks, @shawnbuso ! Ill try.
