### ISSUE TITLE
Autoplay ads

### ISSUE THREAD

**Issue by pozzer1972** [googleads/videojs-ima#53]
There's a way to start advertising video automatically? without the click ?

normal "autoplay" in video tag doesn't work.

Thank you

**Comment by shawnbuso** [comment]
You can auto-play the video by executing the code in the samples' click listener automatically instead of on click. For example, to modify the [advanced sample](https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js) to play automatically, I'd change the following:

1. Remove the following:
```
// Start ads when the video player is clicked, but only the first time it's
// clicked.
this.clickedOnce = false;
this.player.on('click', this.bind(this, function() {
    if (!this.clickedOnce) {
      this.init();
      this.clickedOnce = true;
    }
}));
```

2. After calling ```this.player.ima(...)```, call ```this.init```.

**Comment by anthonyadvertdigital** [comment]
The advanced code doesn't have that exact code? Has it been updated?

I have it setup using the simple example, how would I go about auto-playing the video and the ima sdk?

**Comment by shawnbuso** [comment]
The changes would be similar for the simple sample - currently it's set up in ads.js to respond to a click with calls to the ima plugin. You can just remove the part where it's waiting for a click, and make those calls on page load. Currently the code looks like this:

    // Initialize the ad container when the video player is clicked, but only the
    // first time it's clicked.
    var startEvent = 'click';
    if (navigator.userAgent.match(/iPhone/i) ||
        navigator.userAgent.match(/iPad/i) ||
        navigator.userAgent.match(/Android/i)) {
      startEvent = 'tap';
    }
    
    player.one(startEvent, function() {
        player.ima.initializeAdDisplayContainer();
        player.ima.requestAds();
        player.play();
    });

You want to body of the click listener to run on page load instead of on click, so get rid of all the code in the above snippet except for the body of the listener. All of the code in the above snippet would now be replaced by this:

    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
    player.play();

Now instead of waiting for a click, it will just run on page load. Note that this will **not** work on mobile devices - those devices require the video player to be initialized as the result of a user action, so you would need to call initializeAdDisplayContainer as the result of a click or tap.

If you just want the simple sample to work you can stop reading now :) Below I clear up the confusion with the advanced sample code provided above.

Sorry for the confusion with the previous snippet - I was looking at an older version of the advanced sample. That code in the large snippet has been replaced by the following:

      // Start ads when the video player is clicked, but only the first time it's
      // clicked.
      var startEvent = 'click';
      if (navigator.userAgent.match(/iPhone/i) ||
          navigator.userAgent.match(/iPad/i) ||
          navigator.userAgent.match(/Android/i)) {
        startEvent = 'tap';
      }
      this.player.one(startEvent, this.bind(this, this.init));

**Comment by anthonyadvertdigital** [comment]
Thanks! makes total sense now!

**Comment by sportexholdings** [comment]
Hi!,autoplay not work on my demo.
can you please!, checked the issue:
Link:  http://5th-angle.esy.es/dfp-mat/test-autoplay.php

**Comment by shawnbuso** [comment]
Were you able to take advantage of the snippets I posted further up this issue? It looks like your code is unchanged, and for auto-play to work you'll need to make the changes I mentioned above.

**Comment by sportexholdings** [comment]
Hi!,still the same.

link: http://5th-angle.esy.es/dfp-mat/autoplay.php

not sure what part i need to changed on ads.js

**Comment by shawnbuso** [comment]
It looks like you still haven't made the changes listed above - you still have the code to start the video in an event handler, which you don't want. You'll need to modify your code as outlined  [here](https://github.com/googleads/videojs-ima/issues/53#issuecomment-224606519).

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need help let me know!
