### ISSUE TITLE
Test against VJS 5 and 6

### ISSUE THREAD

**Issue by shawnbuso** [googleads/videojs-ima#539]
contrib-ads 6 allows us to add support for VJS6. Legacy implementations will like still use VJS5 at least for some time. We should investigate adding support for testing against VJS 5 and 6 instead of just one.

**Comment by mysuf** [comment]
Hello, I just tested vjs6.6.3 with contrib-ads6.0.0 and vjs-ima1.2.0. I need to know that all completed (to display related videos) so I created custom event 'allcompleted' like this. It is ugly, but hadn't better idea how to do that.

```
player.on("adsready", () => {
     player.ima.addEventListener(google.ima.AdEvent.Type.ALL_ADS_COMPLETED, () => {
          player.trigger('allcompleted');
	  player.on('ended', () => player.trigger('allcompleted'));
    });
});
```

But player.on('ended') has now delay about 5s. Is this delay expected in new version? I will provide sample page if needed. Thanks

**Comment by ypavlotsky** [comment]
Thanks for the info!

**Comment by incompl** [comment]
`Unexpected endLinearAdMode invocation (State via r)` isn't what I'd expect that error to look like: where it says `r` I would expect it to say something like `ContentPlayback`, `Postroll`, or `AdsDone`. Did it really say `r` or was there a copy/paste issue?

**Comment by mysuf** [comment]
Sorry. I use minified version. I will provide this error with better description;)

**Comment by incompl** [comment]
Ohh, that makes sense. We'll fix this log warning in contrib-ads. This warning is really helpful for debugging these cases. I opened an issue: https://github.com/videojs/videojs-contrib-ads/issues/338

**Comment by mysuf** [comment]
I don't use minified file from contrib-ads/dist. I bundle all together through commonJS, browserify and gulp so I'm not sure if it helps. This is non-minified debug warn msg:

>  video.bundle.js:9852 VIDEOJS: WARN: Unexpected endLinearAdMode invocation (State via AdsDone)

**Comment by incompl** [comment]
Interesting, that suggests that `endLinearAdMode` is invoked after the postroll ad break has already ended. That may be something to investigate in the `videojs-ima` source to verify contrib-ads 6 support.

Another bit of useful information is if you're seeing an `adtimeout` event. In contrib-ads 6, we actually _removed_ a delay before the `ended` event. If you're seeing it later, it may be because the postroll ad is timing out. If your timeout setting is 5 seconds, and the ended event is delayed 5 seconds, that is more evidence that could assist in debugging for sure.

**Comment by incompl** [comment]
I looked at the source a bit and saw `endLinearAdMode` in `reset`. If `reset` can be invoked outside of an ad break (it seems like it can) you may want to consider wrapping the `endLinearAdMode` in `if (player.ads.inAdBreak()) {...}`.

**Comment by mysuf** [comment]
I will provide sample page with non-minified source within hour.. The issue is that it delay every 'ended' event even if all ads are completed (for example after repated playing)

**Comment by mysuf** [comment]
Sample page: https://games.tiscali.cz/player/vjs-testpage.html

**Comment by incompl** [comment]
Interesting, it looks like there is a pause while the player waits for a postroll but no postroll plays, then a postroll timeout, and then the postroll plays after the expected postroll break. This is probably the source of the strange behavior.

Does videojs-ima play postrolls on the ended event? For postroll timeouts and ended events to work correctly, postrolls should play on `contentended`. Here is a relevant except from the [new documentation](https://github.com/videojs/videojs-contrib-ads/):

> * Contrib Ads triggers contentended (EVENT) -- This event means that it's time to play a postroll ad.
> * To play a Postroll ad, start and end an ad break with player.ads.startLinearAdMode() and player.ads.endLinearAdMode().
> * Contrib Ads triggers ended (EVENT) -- This standard media event happens when all ads and content have completed. After this, no additional ads are expected, even if the user seeks backwards.

**Comment by shawnbuso** [comment]
It looks like we are using `ended` instead of `contentended` - I'll create a PR to fix.

**Comment by mysuf** [comment]
There is still uncatched endLinearAdMode() call in onAdBreakEnd. It prints warning when postroll ends.

**Comment by mysuf** [comment]
With @incompl help we probably found another issue using contrib-ads v6 with ima v1.2.1. https://github.com/videojs/videojs-contrib-ads/issues/358. Can you look at it? Thanks.

**Comment by mysuf** [comment]
removed `if (adEvent.getAd().getAdPodInfo().getPodIndex() != -1)` and adstart / adend trigger as expected but contentended still ping together with ended. (and then second time after postroll's adend)

**Comment by mysuf** [comment]
There is also missing trigger `'nopostroll'` on player when postroll is not present. I guess that it resets adtimeout (it was issue with delay at the end of video content). Here is [example](https://github.com/videojs/videojs-contrib-ads/blob/master/examples/basic-ad-plugin/example-integration.js#L108) of integration

**Comment by mysuf** [comment]
In another issue, we talked about complexity of current code. To makes things clear, I rewritten whole plugin. There are temporary _old files to better comparing, because there will be probably some bugs and few features missing (my fork was 48 commits behind your current :X ) You can take a look [here](https://github.com/mysuf/videojs-ima)

**Comment by dilburt** [comment]
Hi Shawn,

I'm responding to #559 and your earlier comment regarding the use of contentended instead of ended for post-rolls. The documentation for VideoJS has always stated that the final event for any series of content and ads will be "ended" so with this change will we still receive an ended event after the final contentended? My designs and I'm sure others have always used ended to determine when everything has completed so it will cause a number of problems if this changes.

Thanks,

Dean

**Comment by Kiro705** [comment]
This issue looks resolved. We test vjs 5 and 6 in our Travis tests
