### ISSUE TITLE
Access Denied to adTagUrl

### ISSUE THREAD

**Issue by yizharm** [googleads/videojs-ima#55]
Hello,
I've taking your sample (Great sample!), but i getting this error:
 "XMLHttpRequest cannot load http://pubads.g.doubleclick.net/gampad/ads?iu=%2F6870%2FYossiTest%2Fvideo&s…u.u_td2_tv1_is0_er8.8.160.308_sv2_sp1_vi0.0.599.1280_vp100_ct1_vb1_vl1_vr1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://imasdk.googleapis.com' is therefore not allowed access."

Player URL - http://player.scepia-sites.co.il/videojs/index.html

Could you please help on this?

**Comment by yizharm** [comment]
I'm sorry it was my mistake!
Ad plays but video is playing in the background also.
Would you please help?
http://player.scepia-sites.co.il/videojs/index.html
Thank you very much!!!

**Comment by tensafefrogs** [comment]
I replied to your other note on the GMF list, but I'll add a note here as well in case anyone else is having a problem like this.

The issue seems to be that your example is throwing a javascript error when trying to call player.remoteTextTracks()

It seems that there was a mistaken commit on video-js or something like that... you may have to adjust your version of video-js or the contrib-ads plugin... I'm not sure what the best fix would be:

https://github.com/videojs/videojs-contrib-ads/pull/61
