### ISSUE TITLE
Support for VAST redirection

### ISSUE THREAD

**Issue by sdahdaah** [googleads/videojs-ima#572]
Hello,

Some of the VAST tags contains a redirection. Currently they do error 1009.

Do you have plans to support VAST ads with redirection anytime soon?

Regards,

**Comment by shawnbuso** [comment]
VAST redirects are currently supported - do you have a sample tag I can look at to see why it's failing? Thanks!

**Comment by sdahdaah** [comment]
Here you go: http://rs.vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw

please load the link on Safari 11 for mac and use user-agent iPhone and check for the error we get, however there is an ad for iPhone but we are not able to handle it through IMA.

Regards,

**Comment by sdahdaah** [comment]
yes i am.

error 400 the VAST tag is correct if you test the same using another 3rd party player with same tag and same conditions it can handle the ad.

make sure to load the page from first with the user-agent iPhone it doesn't show the issue if you load the page with default safari and change later on the agent so make sure to do a reload once user agent is specified.

image attached.

<img width="1323" alt="screen shot 2018-03-21 at 4 38 49 pm" src="https://user-images.githubusercontent.com/36862659/37716201-9e24c7e2-2d26-11e8-8906-99c6e4bef564.png">

**Comment by shawnbuso** [comment]
Hm ok it looks like the issue is that you're getting back an ad that's not supported on iPhone. I tested a few times and sometimes I got a crest ad, but other times I got the error. When I got the error, the ad that came back was a YouTube-hosted AdSense ad, which is not supported. I'd suggest setting up your serving so that these ads aren't returned to iPhone environments.

**Comment by sdahdaah** [comment]
You don't plan to support this? as i said if you try the same with JWPlayer and IMA plugin of JWPlayer there is no issue in it.

**Comment by shawnbuso** [comment]
This is not a matter of redirects - there's no redirect in the tag you're using. The issue is that you're sometimes getting an AdSense ad, and the type of ad that it's returning is not supported by the IMA SDK on iPhone. It's not an issue with the plugin, it's an issue with the IMA SDK - I took your VAST response and put it into our [IMA SDK sample](http://googleads.github.io/googleads-ima-html5/advanced/), which is using the IMA SDK directly and not the video.js plugin, and it's not working there either. This is expected behavior for any implementation using the IMA SDK.

The ad tag you're using is returning different ads each time I request it, so it could be that when you're testing with JW it just happens to be returning ads that are supported.

**Comment by sdahdaah** [comment]
Hello Shawn,

i am sure from my words. It can't be a coincidence that it never fails on JW while it always fails with us.

Attached the video.
[ads.mp4.zip](https://github.com/googleads/videojs-ima/files/1834397/ads.mp4.zip)

**Comment by shawnbuso** [comment]
Could you send me the ad tag that you pasted into the JW page? Thanks!

**Comment by sdahdaah** [comment]
Sure it is the same one we are using in our page: https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on

**Comment by shawnbuso** [comment]
Hmm ok are you able to reproduce this in our [sample](http://googleads.github.io/videojs-ima/examples/advanced/)? That will tell us if the issue is in the plugin or in your specific implementation of the plugin.

**Comment by sdahdaah** [comment]
It doesn't run at all when i choose the user-agent as iPhone it doesn't even call the ad on the page given.

**Comment by sdahdaah** [comment]
Same problem i tried directly from my iPhone it doesn't play.

![img_8270d00eec33-1](https://user-images.githubusercontent.com/36862659/37728983-638a3310-2d44-11e8-8c94-1cf2deddb03a.jpeg)

i tried the same from the same device on JWPlayer using IMA it plays.

![img_2082](https://user-images.githubusercontent.com/36862659/37729050-96ba793e-2d44-11e8-8cdc-4de4085c2afc.PNG)

**Comment by shawnbuso** [comment]
OK thanks for the info, I'm able to somewhat reproduce now - when I request your tag in my debug setup it just loads forever, it never plays. It's not an issue with the redirects, because it does follow them until it finds an ad, but the VPAID ad it ultimately gets is giving it problems. I'm going to work with the rest of the team on this and see what we can find. Thanks!

**Comment by ypavlotsky** [comment]
No updates yet, I'll comment on this issue when I hear something.

**Comment by sdahdaah** [comment]
Thank you Ypavlotsky. Hopefully we see that fixed in the next release.

**Comment by shawnbuso** [comment]
Hi there - I spoke to the rest of the IMA team, and they think this could be an issue with the VPAID playback. It looks like when the ad receives invalid VAST, it's throwing an internal exception, which is never caught, and then just hangs. Can you ask the ad creator to wrap the ad playback code in a try, and then in the catch call the ad error VPAID callback?

**Comment by sdahdaah** [comment]
hello,

this ad tag is a google adsense tag given by google to verify that you are
eligible for adsense.

i doubt we can contact them and i doubt there is an issue with it as i
already demonstrated it is working with other players with no issue example
JWPlayer.

**Comment by shawnbuso** [comment]
Hi there - did you change the serving settings on that tag? Before I was seeing VPAID with redirects, but now I just get a YouTube hosted video ad with no redirects and no VPAID.

**Comment by sdahdaah** [comment]
Hello Shawn,

as previously mentioned i don't touch the tag it is a google tag that is
provided for verification prior allowing adsense.

you can find it here:
https://support.google.com/adsense/answer/6054303?hl=en

Regards,

**Comment by shawnbuso** [comment]
Thanks for the info - I'm no longer seeing this issue when I paste [that tag](https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on) into our [sample player](http://googleads.github.io/videojs-ima/examples/advanced/). Are you still able to reproduce this?

**Comment by sdahdaah** [comment]
I am not seeing the issue anymore too!! Weird!!
