### ISSUE TITLE
Can not play HLS ad on Firefox?

### ISSUE THREAD

**Issue by vungocastis** [googleads/videojs-ima#589]
I can play the HLS AD normally on Safari (natively support HLS) but not on Firefox.
I can play HLS main video normally with videojs 6 and videojs hls plugin so i don't understand why HLS ad can not be played.
Error console log is:

> **_Ad error: AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities_**

VAST sample file is attached with this post.
Any suggestion is very much appreciated.

[vast_video.xml.zip](https://github.com/googleads/videojs-ima/files/1894227/vast_video.xml.zip)

**Comment by shawnbuso** [comment]
The IMA SDK can only support ads that the native video element for that browser can support. It uses it's own video player to play ads - it doesn't re-use the content player. So what's happening is your VAST response has only one media file, which is an m3u8, but the sdk can't play it because it's using the browser's native video element to play ads, which doesn't support m3u8s.

**Comment by vungocastis** [comment]
Ah i see. Thanks for your info.

**Comment by ikad95** [comment]
Is there any workarounds?
