### ISSUE TITLE
Fallback not working when autoPlayAdBreaks off

### ISSUE THREAD

**Issue by davidjamesherzog** [googleads/videojs-ima#662]
Fallback ads work when autoPlayAdBreaks is on.  When autoPlayAdBreaks is off, code execution just halts.  I've created two codepens to demonstrate this.  Is there something else that needs to be done programatically when autoPlayAdBreaks are off?

**With autoPlayAdBreaks off**
https://codepen.io/davidjamesherzog/pen/eKELjN

**With autoPlayAdBreaks on**
https://codepen.io/davidjamesherzog/pen/dKVNRB

**Comment by shawnbuso** [comment]
I'm having trouble with your samples - it looks like they're trying to load a controller.js that doesn't exist. Are they still working for you on your end?

**Comment by davidjamesherzog** [comment]
For both examples, click on the `Play Video` button below the player to start the ads.  The first link above does not do anything but it should play the fallback ad (which is why I opened this issue).  The second link should play the fallback ad successfully.

**Comment by davidjamesherzog** [comment]
I removed the reference to `controller.js`.  That was a copy/paste error.

**Comment by shawnbuso** [comment]
I think this issue goes beyond autoPlayAdBreaks - if I take your first example and just remove `autoPlayAdBreaks: false`, it still doesn't work. If the issue was with that mechanism, I would expect that change to fix it. It looks like you have a lot of other custom code going on in there - setting the ad tag and requesting ads on click instead of on page load, and adding your own CONTENT_RESUME_REQUESTED listener. Could you give me an idea of what you're trying to do with that code so we can see a) if it's doing what you want it to do, and b) if there's a better way to do it?

**Comment by davidjamesherzog** [comment]
@shawnbuso - Sorry, but I was pulled off on other work and I am finally getting back to looking at this.  I took the advanced example from this repo.  I added `autoPlayAdBreaks: false` to the options and I added the following ad break listener:

```
var _this = this;
this.player.ima.setAdBreakReadyListener(function() {
  _this.player.ima.playAdBreak();
});
```

If I use the following sample URLs it works the same whether or not I set autoplay ad breaks on or off:

normal - http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&vid=short_onecue&correlator=
error - https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirecterror&nofb=1&correlator=

If I use the fallback URL, it works when autoplay ad breaks is set to true but not when it is set to false (no fallback ad plays).

fallback - https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirecterror&correlator=

**Comment by shawnbuso** [comment]
Hmm the issue here may be that your fallback tag is a single ad, while the working tag is a VMAP response. Manual ad break playback only works with VMAP or ad rules responses, since you can start a single ad responses whenever you want by changing the timing of adsManager.start(). However I don't think this is supported yet with the IMA plugin - you can't delay the call to adsManager.start() with single ads. We can take that as an FR, though.

**Comment by davidjamesherzog** [comment]
The fallback tag is the sample one Google provided.  I'll pass this info off to our Ad Ops team.  We do plan on using VMAP so hopefully they can setup an example that will work.  Thanks for the info!
