### ISSUE TITLE
UI controls obscure overlay ads intermittently

### ISSUE THREAD

**Issue by holdcroft** [googleads/videojs-ima#69]
The VideoJS UI controls intermittently hide approximately half of non-linear overlay ads.

This appears to be the case if the play button is clicked prior to the VideoJS initialization process being fully completed.  To replicate, run a non-linear overlay ad tag and click the play button as soon as the page loads. It looks like it takes a little time for the 'vjs-user-active' class to be added.

**Comment by shawnbuso** [comment]
It looks like this may be a video.js bug. We rely on their user-active and user-inactive classes to bump the ad container when the controls are shown. With their current implementation, if you click the play button very shortly after it loads, they (for some reason) don't add the user-active class, so we don't bump our ad, because we don't know that the user is active. I have a workaround in place that should resolve this.
