### ISSUE TITLE
I need "adserror" event

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#690]
Hi all,
i need "adserror" event but i saw that this event was deprecated..
what's the equivalent event???
i wait for the answer.
Thanks a lot,

A.

**Comment by ypavlotsky** [comment]
Hi,

`adserror` is an event that has special meaning in videojs-contrib-ads, and that meaning is going away, but the event can still be raised by the plugin and you can respond to it in the way you see fit, so that's not going away, AFAIK. Source: http://videojs.github.io/videojs-contrib-ads/integrator/api.html.

@incompl, does that sound correct?

**Comment by incompl** [comment]
Correct!

**Comment by ibraalek10** [comment]
Hi, 
thanks for the answer, but I have another question,
How can I intercept the "adserror" event???
Before I used this syntax:

> player.on('adsready', function () {
>     ..............
> });

Now this syntax doesn't works.
Thanks for all,

A.

**Comment by incompl** [comment]
That syntax will work, are you sure an adserror event is happening?

**Comment by ibraalek10** [comment]
Yes.. 
The difference respect of some time ago is that in console doesn't go out a console.error but a console.warn than when the error happens I can't intercept it.

A.

**Comment by ypavlotsky** [comment]
We're using that syntax to pick up the `adserror` event and it's working for us. You do have to encounter an actual ads error for it to trigger, like a VAST redirect error: [sample tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirecterror&nofb=1&correlator=).

**Comment by ibraalek10** [comment]
Hi,
In this screenshot, my vast goes in error and this error is reported by a console.warn..
In this situation, "adserror" event doesn't catch the vast error!!!

![schermata 2018-07-20 alle 11 54 33](https://user-images.githubusercontent.com/23355148/42996734-b4c6fc0c-8c14-11e8-8573-ff86e9395e03.png)

A.

**Comment by ypavlotsky** [comment]
Is your ad part of a playlist? If it's in a playlist, the SDK will wrap errors in log() messages because all errors in the SDK are supposed to be fatal and there may still be more ads to play. We have a feature request open to expose these log messages [here](https://github.com/googleads/videojs-ima/issues/698).

**Comment by Kiro705** [comment]
Closing this issue because https://github.com/googleads/videojs-ima/issues/698 was resolved. Please see this commit for the changes https://github.com/googleads/videojs-ima/commit/3b1675889a6d595eebcf4c43620354537c850bce.
