### ISSUE TITLE
Related to issue 72 - feel free to close.

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#73]
I can't reply to you, because you are closing the issues (and comments there are forbidden), prior to having a chance to explain anything. Feel free to close this as well, but I just want to make my point. Then it is your decision how to proceed (obviously, you already taken it).
This is related to: https://github.com/googleads/videojs-ima/issues/72

----------------------

No, I don't complain against DFP/DFP SB.
But you are not trying to understand the issue and only find reason to close it.

With other VAST solutions for other players like Flowplayer and JW Player, you can run mid,post-rolls and overlays with DFP/DFP SB. As their architecture allows you to call different VAST tags on different positions during the video. However this plugin only allows single position, which is presumed (by the plugin) to be pre-roll.

The only solution to have mid,post-rolls and overlays is to have VMAP. VMAP is not widely supported.

**Comment by tensafefrogs** [comment]
The goal of this project is to provide a simple way to integrate videojs and the IMA SDK. The IMA SDK already supports midrolls and other scheduling via VMAP, so adding that kind of functionality to the plugin would just create duplicate code and duplicate ways of playing a midroll.

Additionally, VMAP is a much better solution as it allows your ad trafficker to change the ad positions and rules all in one place, rather than having to set up some extra CMS or release a new version of your site to change things.

**Comment by shawnbuso** [comment]
I see what you're saying now, and @tensafefrogs's answer is the path we've decided to take. If you're looking for mid- and post-roll support, we recommend VMAP responses as they are industry-standard and well supported by the plugin.
