### ISSUE TITLE
Learn More Enhancement / Support

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#743]
Support in ima plugin,  need to show Learn More in Desktop too, Can we able to change Learn More text and How do we add "Learn More" stuff in VAST tag , correct me if i am wrong.

**Comment by Kiro705** [comment]
Hi @Kumaran29 ,

Right now we show `Learn More` on mobile for ad click-through, because clicking on full screen ads pauses the ad and does not click through.

`Learn More` is not needed on desktop because clicking on the ad provides ad click-through.

Does that answer your question?

I am closing this issue, but feel free to reopen if anything related comes up.
