### ISSUE TITLE
VAST error 1012: Unable to request ads from server due to network error.

### ISSUE THREAD

**Issue by nanek** [googleads/videojs-ima#764]
I'm logging lots of VAST errors 1012. Unable to request ads from server due to network error.

I see this error 10 times more than any other VAST errors. Any ideas on what could cause this error or where to find more information? Thanks!

I don't believe it is a network error as I'm logging the error and due to the high rate of error. I'm not sure which library/service is returning this this error. We are using DFP as our ad server.

**Comment by dilburt** [comment]
We've noticed this as well. It was the highest error for us a couple of days ago. I cannot find a cause for these.

**Comment by mysuf** [comment]
Look if these errors occurs mostly between some hours (traffic peaks). Its possible that ad publisher refuses connection due to poor load balancing.

**Comment by cameronchurch** [comment]
Not sure if you guys are still have the issues or if others arriving here are but thought I'd chip in as we have been seeing this across our network of customers. 

A couple of things - we're maintaining a unified glossary of error codes here https://watchingthat.com/guides/ima3-vast41-brightcove-jw-ad-error-codes/ if that helps anyone going forward.

Regarding 1012 I've been in contact with IMA support - their position is:
"The 900 error [which is the VAST error code] (This is the result of an unknown VAST 3 error, which likely stopped the ad request.) is thrown by the ad server to let the developer know that there's something wrong with the VAST XML. The XML can be invalid or malformatted, some characters might need to be escaped etc. The error caused by the XML file is caught by the IMA SDK which throws the 1012 error code to tell you the ad request was interrupted/stopped by the server. Hence the 1012 error code description as: "There was a problem requesting ads from the server. IMA Error code 1012." Since the issue is with the ad server, it is recommended to reach out to the DFP Support Team. 
No 900s are available in their [DFP] VAST error report because the VAST XML hasn't been requested (900 request was stopped by VAST 3 error)"

Their proposed solution is to run the ad tag in a browser, get the XML and review it for formatting issues and submit it to Google Support for review.  

We're doing that now on a customer by customer basis and can revert here with our findings.  We're also wondering if there has been some change/break in the IMA core that has seen these 1012 come up out of the blue.  Last year our data showed something very similar happen with an IMA release.  So it could be another episode. 

If you want a full spectrum review of all 1012 errors (and indeed all other errors) you have in your inventory feel free to reach out direct - our platform does exactly that!
