### ISSUE TITLE
Ad replacing <video> src on iOS 12

### ISSUE THREAD

**Issue by mur1s** [googleads/videojs-ima#769]
Hello,

I have a strange issue with the IMA3 SDK on iOS 12. The video ad replaces the source from the main video. Here is an example:

http://staging53.wendyshow.com/ios12bug/

Scenario:
- The main video should autoplay.
- The ad should appear below the main video after 5 seconds (setTimeout()).
- After the ad has ended, the main video should continue playing.

It works as expected on any device I was testing with, except on iOS 12.

Thanks,
Muris

**Comment by Kiro705** [comment]
Hi @mur1s,

I wanted to check if this error is still happening for you. I attempted going to the test page, but it was unavailable.

**Comment by mur1s** [comment]
Hi @Kiro705,

We have recently switched to the Brightcove player (video.js) and everything is working fine there. The bug still appears in a custom HTML5 video player, here is an old pen with an example: https://codepen.io/mur1s/pen/mQyYVp

I've just checked it on iOS 13.1.

**Comment by pradhyumn94** [comment]
@mur1s You can work around it  by  assigning a fake video  tag to your  IMA3  class rather than   tag actually being used to  play  content.

**Comment by mur1s** [comment]
@pradhyumn94, I have already implemented a workaround by adding a second video tag for IMA and it worked. It was just weird to me that IMA doesn't create its own video tag on iOS.

**Comment by gschoppe** [comment]
Hi @mur1s and @pradhyumn94,

It looks like you are running into the expected behavior of the IMA SDK on iOS. The IMA SDK normally defaults to creating and using a second video element to play ads, but in the case of certain older versions of Android and of iOS, this causes a problem.

iOS's default video playback behavior is to play web videos in its own native instance of AVPlayer, rather than in the actual browser. This prevents the IMA SDK from being able to properly switch from one video element to another, so it has to instead replace the source of the video that is currently playing, instead. This also prevents iOS from supporting skippable ads, by default.

With iOS 10, apple added the playsinline attribute to the video element, which can be used to play videos in the same manner as on other systems. If you add this attribute to your video, and then call `google.ima.settings.setDisableCustomPlaybackForIOS10Plus(true);` before the adsLoader is instantiated, a second player should be created for the ad.

You can find more information about this setting on the [mobile skippable ads documentation](https://developers.google.com/interactive-media-ads/docs/sdks/html5/skippable-adsl) for the IMA SDK.

**Comment by jackfinn88** [comment]
Hi, I'm getting this issue and the playsinline + setDisableCustomPlaybackForIOS10Plus fix didn't seem to resolve it. Also, the link you included is dead now I think.

Is there any other solution or suggestion for this?

**Comment by Kiro705** [comment]
Hello @jackfinn88 ,

The link had a typo, it should be https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/skippable-ads

Let me know if that helps, but if not feel free to open a new issue with steps to reproduce.
