### ISSUE TITLE
Ad background flashing with some ad sources e.g. Rubicon

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#785]
Hi there,
when using Rubicon for example there is a black background flashing whenever the tag is being called and no ad returned. 
Some of the players like jw solved this bad UX by displaying their own loading indication until an ad actually renders.

I have created this simple vast waterfall for testing and included the rubicon tag three times so it is properly visible on a fast connection:
https://api.assertcom.de/videoads/rubicon/?h=300&w=480&pageurl=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads%2Fdocs%2Fsdks%2Fhtml5%2Fvastinspector&referrer=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads%2Fdocs%2Fsdks%2Fhtml5%2Fvastinspector&uuid=&type=vast

Please give it a try:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector
https://developer.jwplayer.com/tools/ad-tester/ (make sure to select IMA SDK)

**Comment by Slind14** [comment]
@ypavlotsky is there any way to only render the ad container when an ad is actually available? Quoting the engineers from Rubicon:

>    display of the container should not occur up until the point that the ad can successfully render

**Comment by arnaudcasame** [comment]
Hi,

I've investigated the Rubicon ad tag you shared and I was able to reproduce the issue (black background flashing, vastErrorCode: 900, AdErrorCode: 1021). However, given the AdErrorCode and vastErrorCode, the issue is not with the videojs-ima plugin, it is with the VPAID creative embedded in your VAST XML. If you take a look at the IMA SDK for HTML5 [reference](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis) page, you'll see that there was an error with the asset fallback. The VAST error 900 code is caused when any VAST 2 error occurs, even if VAST 3 is requested or your network default is set to VAST 3.
In such case, it is recommended you to:

- Either begin to request [VAST 3](https://support.google.com/admanager/answer/4517679) or [enable VAST 3 for your network](https://support.google.com/admanager/answer/4517679#enable).
- Work with your ad provider to troubleshoot the exact issue, or respond with [VAST 3](https://www.iab.com/guidelines/digital-video-ad-serving-template-vast-3-0/)

Regards,
Arnaud

**Comment by Slind14** [comment]
Thanks @arnaudcasame 

We are using VAST3 for the waterfall, already. Do you mean the rubicon tags? I don't think they are using DFP to ship those. Anyhow they say the VPAID version is mandatory, otherwise they won't send demand.

**Comment by arnaudcasame** [comment]
Hi,

Yes, I meant the Rubicon VAST responses are v2.0, try serving them using the [VAST 3](https://support.google.com/admanager/answer/4517679) or [enable VAST 3 for your network](https://support.google.com/admanager/answer/4517679#enable). If you still encounter the same issue, work with your ad provider to troubleshoot the exact issue, or respond with VAST 3.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
