### ISSUE TITLE
Unexpected preroll and postroll event warnings

### ISSUE THREAD

**Issue by dilburt** [googleads/videojs-ima#788]
Hi,

I'm getting "WARN: Unexpected startLinearAdMode invocation (Preroll)" warnings under some ad conditions and "WARN: Unexpected readyforpostroll event" in others.

I'm not sure what might be triggering the preroll warnings but I get the same warning running your Autoplay example. The only changes I made in it was to remove poster.jpg, replace the bunny video with https://cdn.applixir.com/blank.mp4 and set "Verbosity" to 5 in order to get more log data.

The Unexpected postroll warnings appear to be related to receiving an empty wrapper so if you have an empty wrapper test ad you should be able to generate that quickly enough.

Let me know if I can send you any additional information.

Thanks,

Dean
Applixir

**Comment by Kiro705** [comment]
Hello Dean,

I was looking at our [autoplay example](https://googleads.github.io/videojs-ima/examples/autoplay/) and did not see the warnings you mentioned.

I believe the empty postroll bug was fixed in [v1.7.2](https://github.com/googleads/videojs-ima/releases/tag/v1.7.2) of the plugin.

If possible could you verify this issue is still reproducible?

Thanks,
Jackson
IMA SDK DevRel
