### ISSUE TITLE
WARN: Unexpected adsready event (Preroll)

### ISSUE THREAD

**Issue by huangdaman** [googleads/videojs-ima#801]
HI，
  I use changeAdTag() and make a new ad request on ALL_ADS_COMPLETED event. 
On the browser it work fine but on the Tizen TV will get an error _WARN: Unexpected adsready event (Preroll)
Even_ in tizenTV, there will be occasional successful playback.
can you help me ?

if (event.type == google.ima.AdEvent.Type.ALL_ADS_COMPLETED) {
      player.ima.changeAdTag('newUrl'); // really null
      player.ima.requestAds();
  }

**Comment by huangdaman** [comment]
And how do I call adsLoader and then run adsLoader.contentComplete()

**Comment by arnaudcasame** [comment]
Hi,

The issue seems to be with the Tizen TV web platform since your implementation works fine on regular browsers. I was not able to replicate the issue using our [Inline Skippable ad tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=). Can you share the ad tag you were using when you encountered the issue?

**Comment by huangdaman** [comment]
Thinks,
This is indeed a problem with TizenTV, or I need to use other methods.

**Comment by zgzong** [comment]
@huangdaman  do you enable the autoplay for the player? If so, please try disable it.

**Comment by huangdaman** [comment]
yes! I setting the response with xml string, and it work
