### ISSUE TITLE
[iOS/Safari] AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.

### ISSUE THREAD

**Issue by gcarrion-gfrmedia** [googleads/videojs-ima#803]
Hi!

We're using **VideoJS 7.5.5** and the **videojs-ima** plugin. We're having issues playing preroll linear ads in iOS.

Initially, the first issues we got was the error `Error 200 - The provided ad type: skippablevideo is not supported.`.

After searching online, we found that adding the `playsinline` attribute on video tag and the `disableCustomPlaybackForIOS10Plus: true` in the SDK config should fix that problem. but did the changes and it does not work, and now is showing another error: `Ad error: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.`

The thing is, the player did not have autoplay on, we use `can-autoplay` and only set autoplay config if is allowed with sound, otherwise we set autoplay false. And in this case, the player is not autoplaying, and the user's click to play was required, but somehow the ads triggered that error that needed user interaction when there was one.

Here I have a demo page with a preview ad that it can show the error [http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=B1_UT7D8NdAYpfHg5wUwpY2W7wWIAYCAgKDH1Jq0rQE&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html?autostart%3Dtrue&redirect_hash=AJlzBa3G3G748uARIaCshj8gNCKxUfzFvQ&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2Xwv5hw)

Has anyone seen this issue?

**Comment by arnaudcasame** [comment]
Hi,

I've investigated the test page you shared and noticed that you have a url parameter called **autostart** set to true, this is causing your video content to autoplay. If you set it to false, the `UNMUTED AUTOPLAY IS NOT ALLOWED` and the `AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.` messages will disappear.
On the other hand, if you want to autoplay your videos, the video player must be **muted** and the videojs-ima plugin options must have `adWillPlayMuted : true`.

**Comment by gcarrion-gfrmedia** [comment]
Hi @arnaudcasame!

Thank you for your help.

Yes, the links have a URL parameter called autostart set to true, but what that does is, it uses `can-autoplay` feature detection in HTMLMediaElement and only set autoplay config to true if it detects that autoplay with sound is allowed, otherwise, we set autoplay false when rendering the player.

Normally, on desktop, it will check and it will autoplay if unmuted sound is allowed, but on mobile, where autoplay with sound is not allowed, it will require the user to click the player to start.

This link is the same preview ad, but without the autostart URL parameter set to true. On the iPhone the behaviour happens the same, when clicked to play it looks like is starting the ad, but it fails, then it continues to the main video.
[http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=W8o3efjjqBUY8-Pg5wUw8_-V7wWIAYCAgKDH1Ir_JA&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html&redirect_hash=AJlzBa2hWWXq5GNQ1Zyei2T2-OL8J9OMeA&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2EWLi8c)

Here is a screen recording of that last link opening on the iPhone. Notice that it tries to play the ad, but it fails, then it continues with the main video.
https://drive.google.com/file/d/1unDouCAQhAaMADotmpEqbNrlVaAqAZTo/view?usp=sharing

Thank you!

**Comment by dioramayuanito** [comment]
you should use adWillAutoPlay and  adWillPlayMuted

**Comment by gcarrion-gfrmedia** [comment]
Hi @dioramayuanito 

Thanks for your reply.

Initially, we weren't using those settings because we've read that they were deprecated and as stated in issue 504 and the comment by @ypavlotsky 
> We've deprecated the adWillPlayMuted setting in our plugin because the plugin now deduces it from whether the player is muted or its volume is 0.
https://github.com/googleads/videojs-ima/issues/504#issuecomment-389947657

So we were letting the player's setting determine if autoplay or not and use that config.

However, we just added those settings to the configuration as you mentioned, but it has no effect, the same issue persists. 

It can be replicated in either an actual iOS device, an emulator and even in Chrome with iOS's User Agent, the same error is triggered. So it seems is just throwing that error based on the UA and not based on a device capability/limitation. Screenshot in Chrome emulating iOS UA: https://take.ms/7SjUP

You can see the updated player configuration with those settings in place in the same above links from previous comments.

Any other suggestion?

**Comment by dioramayuanito** [comment]
i use adWillAutoPlay and adWillPlayMuted with can-autoplay and everything works fine for autoplay html5 setting https://m.detik.com/20detik/technology

**Comment by dioramayuanito** [comment]
sorry, autoplay of 20.detik.com is here https://m.detik.com/20detik/e-flash/20190605-190605037/dear-netizen-kominfo-ajak-kita-posting-minta-maaf-dan-setop-hoax---

**Comment by arnaudcasame** [comment]
Hi,

You can't use the `can-autoplay` feature if you're not autoplaying your content and ads, using it makes the plugin assume that you're autoplaying your videos (content and  ads) which makes the browser stop the ad playback (because autoplaying media unmuted is prohibited by certain browsers) and then the IMA SDK throw the exception `AdError 1205: The browser prevented playback initiated without user interaction.`

If you wanna use the `can-autoplay` feature, you gotta make sure the videojs player is muted.

**Comment by gcarrion-gfrmedia** [comment]
Hi @arnaudcasame ,

Sorry for the confusion, I wasn't clear enough. 

When I mentioned `can-autoplay`, is actually only used when the player is set to autoplay. If the player has no autoplay set, it will not use `can-autoplay`. 

In this example, that autoplay is not set, it will not use `can-autoplay` and anyway is giving the error `200 The provided ad type: skippablevideo is not supported`. This happens on iOS and in-browser UA spoofing.
Screenshot: https://take.ms/41zgb
Link: [http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=W8o3efjjqBUY8-Pg5wUw8_-V7wWIAYCAgKDH1Ir_JA&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html&redirect_hash=AJlzBa2hWWXq5GNQ1Zyei2T2-OL8J9OMeA&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2EWLi8c)

In this other example, it has autoplay and it uses  `can-autoplay`. In the case it detects autoplay with sound is *not* allowed, the player won't try to do autoplay at all, not even muted. So basically on mobile, it will always require a click to play. In this scenario, it throws the error `Ad error: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.` (this happens on the actual device or iOS emulator)
[http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=B1_UT7D8NdAYpfHg5wUwpY2W7wWIAYCAgKDH1Jq0rQE&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html?autostart%3Dtrue&redirect_hash=AJlzBa3G3G748uARIaCshj8gNCKxUfzFvQ&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2Xwv5hw)

What could we be missing here?

**Comment by dioramayuanito** [comment]
in my case, can-autoplay works fine if you run can-autoplay before you make videojs instance. can-autoplay will give result: browser maybe can autoplay unmute, browser maybe can autoplay mute, or browser maybe cannot autoplay.

in your case, this can-autoplay result always produce 1 result: browser  is autoplay unmute. this is probably wrong.

**Comment by dioramayuanito** [comment]
bcoz your script has been minified i dont know where is the implementation of can-autoplay in your site. 😁

**Comment by dioramayuanito** [comment]
https://ibb.co/fMvjYw1

**Comment by dioramayuanito** [comment]
i make a screenshot with WebView Test (a variant of Chrome Android you can install it via Google PlayStore), it looks your videojs configured always with: autoplay is true, mute is true, and this is probably bad result of can-autoplay.

**Comment by dioramayuanito** [comment]
so the procedure you should create in your script is : 1. run can-autoplay, 2. can-autoplay results is the browser type of its autoplay and its mute, 3. copied those result into videojs autoplay and mute, 4. the last is make videojs instance.

**Comment by arnaudcasame** [comment]
Hi,

In your first example, where the `error 200 The provided ad type: skippablevideo is not supported.` is being thrown, the IMA SDK for HTML5 doesn't support skippable ads when the video doesn't play inline in Mobile Safari. The only way to display skippable ads on Mobile Safari is to set the player playsinline attribute to true. You'll find more details about this issue [here](https://ads-developers.googleblog.com/2017/06/new-custom-playback-apis-for-ima-html5.html)

In the second example, where the `Ad error: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.` is being thrown, the issue is with the fact that the browsers (Safari and Chrome) made some important changes to the auto-play policies. These changes provide users the ability to browse the web with fewer distractions, particularly in the form of relief from websites that auto-play with sound. If you want to autoplay videos, you'll want to update your implementation to handle these new policies. In order to autoplay your videos on iPhones, you need to set your player's muted attribute to true and also set its playsinline attribute to true (see the example below). You'll find more details about the autoplay feature on iPhone [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/autoplay#autoplay_on_iphone).

```
<video id="contentElement" playsinline muted></video>
```

**Comment by gcarrion-gfrmedia** [comment]
Thank you @dioramayuanito and @arnaudcasame

My apologies that didn't link to the unminified source code and that there's a lot of information that might be confusing.

Let's try to focus on just one of the scenarios at a time to avoid further confusions.

Playing skippable videos on iOS with the IMA HTML5 SDK requires that `playsinline` is used along with `disableCustomPlaybackForIOS10Plus: true`. We do have both but is not working on our end.

Here is where we construct the player with the `playsinline`
https://github.com/ApexTech/gfr-player/blob/refactor/src/embed/players/nativePlayer.js#L42

And here is where we set the `disableCustomPlaybackForIOS10Plus: true`:
https://github.com/ApexTech/gfr-player/blob/refactor/src/plugins/gfr_ads.js#L9

This example link below does not have autoplay set and it does not use `can-autoplay` to detect autoplay capabilities. So is just the player with no autoplay waiting for the user to click play.
[http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=W8o3efjjqBUY8-Pg5wUw8_-V7wWIAYCAgKDH1Ir_JA&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html&redirect_hash=AJlzBa2hWWXq5GNQ1Zyei2T2-OL8J9OMeA&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2EWLi8c)

However, when clicking the player to start playback (on iPhone or an iOS Emulator, no browser UA spoofing), then it throws the error `[ima.common.ErrorUtils] Error play dispatched: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.`

Screen recording: https://take.ms/xv4gA
Screenshot: https://take.ms/WLVhw

Notice that the ad tries to start playing, you can see the IMA Advertisement UI briefly before it throws the 400 error.

Being autoplay false and that we have `playsinline` is used along with `disableCustomPlaybackForIOS10Plus: true`, what could be causing that it gives that error when trying to play the ad?

Thanks!

**Comment by dioramayuanito** [comment]
maybe your configuration of VideoJS id !== VideoJS-IMA id ???

**Comment by dioramayuanito** [comment]
please follow this simple example https://github.com/googleads/videojs-ima/blob/master/examples/simple/ads.js

**Comment by dioramayuanito** [comment]
https://github.com/googleads/videojs-ima/blob/master/examples/simple/index.html

**Comment by arnaudcasame** [comment]
Hi @gcarrion-gfrmedia,

Your first test page is successfully showing skippable video ads on iOS Safari emulator (see screenshot below)
![videojs_skippable_ads_on_iOS](https://user-images.githubusercontent.com/12627484/59384230-bb7cac00-8d2f-11e9-9f29-f63291d794db.png)

The player on your second test page has the autoplay attribute set to true, this is causing your ad to not display since the muted attributed is missing (see screenshot below). Please remove the autoplay attribute from the player setting so that the IMA SDK doesn't throw the `AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.` when you click play.
![video_autoplay_but_not_muted](https://user-images.githubusercontent.com/12627484/59384588-86bd2480-8d30-11e9-9bf5-a4b4fe43cf5a.png)

**Comment by gcarrion-gfrmedia** [comment]
Hi @arnaudcasame! 

That's because it was UA spoofing from Chrome. On the actual device (or the XCode emulator) is where the errors happened.

However, we found a solution based on the simple example that @dioramayuanito shared and the help of our great developer @markmercedes. 

We added these lines to our ads.js file and along with what we already had (`playsinline` and `disableCustomPlaybackForIOS10Plus: true`):

```
this.startEvent = this.startEvent.bind(this);
    this.initAdDisplayContainer = this.initAdDisplayContainer.bind(this);

  startEvent() {
    if (
      navigator.userAgent.match(/iPhone/i) ||
      navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)
    ) {
      return "touchend";
    }

    return "click";
  }

  initAdDisplayContainer() {
    this.player.ima.initializeAdDisplayContainer();
    this.player.el_.removeEventListener(
      this.startEvent(),
      this.initAdDisplayContainer
    );
  }

    this.player.el_.addEventListener(
      this.startEvent(),
      this.initAdDisplayContainer
    );
```

Adding those lines fixed the issues we had, on both autostart and manually click-to-play.

You should see it working correctly now on the sample links:

With autostart using `can-autoplay`: [http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=B1_UT7D8NdAYpfHg5wUwpY2W7wWIAYCAgKDH1Jq0rQE&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html?autostart%3Dtrue&redirect_hash=AJlzBa3G3G748uARIaCshj8gNCKxUfzFvQ&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2Xwv5hw)

Without autostart: [http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=W8o3efjjqBUY8-Pg5wUw8_-V7wWIAYCAgKDH1Ir_JA&op=set&redirect=https://player-qa.gfrvideo.com/player/255502.html&redirect_hash=AJlzBa2hWWXq5GNQ1Zyei2T2-OL8J9OMeA&lineItemId=5076730461&creativeId=138271786265](https://bit.ly/2EWLi8c)

Thank you all for the support.

**Comment by dioramayuanito** [comment]
👍

**Comment by gcarrion-gfrmedia** [comment]
Can any collaborator close this issue since is fixed? Thanks, everyone!

**Comment by adamvaul** [comment]
This link helped alot:

https://developers.google.com/interactive-media-ads/docs/sdks/html5/autoplay#autoplay_on_iphone

When I create the video element for the player to attach to I specify these properties explicitly on iPad or iPhone:

<video id="contentElement" playsinline muted>
    <source src="https://storage.googleapis.com/gvabox/media/samples/stock.mp4"></source>
  </video>

BUT THAT IS NOT ENOUGH:

When I initialize the videoJS player via an options argument I make sure to set muted to true there as well so as not to override what I put in the html above:

// if apple device
videojs('contentElement', { **muted: true**, ... other options);
