### ISSUE TITLE
mouseenter/mouseleave handlers prevent SKIP AD button click in iOS

### ISSUE THREAD

**Issue by opinxit** [googleads/videojs-ima#808]
In iOS, the mouseenter/mouseleave handlers attached to the div.ima-ad-container to show/hide the ad controls "hijacks" a first click/tap on the ad player with the result that it takes two clicks to press the SKIP AD button, which is frustrating for users. 

The code in question: https://github.com/googleads/videojs-ima/blob/master/src/ad-ui.js#L129:

```
  this.adContainerDiv.addEventListener(
      'mouseenter',
      this.showAdControls.bind(this),
      false);
  this.adContainerDiv.addEventListener(
      'mouseleave',
      this.hideAdControls.bind(this),
      false);
```

Since the controls are shown/hidden on ad pause/play anyway, can a check for iOS (or native support for mouseenter/mouseleave) be made before attaching these handlers?

Or failing that, can a click on the SKIP AD button not be swallowed by this handler? and/or perhaps the ad ui ought to be redesigned to make it explicit what maximizes/minimizes the ad controls -- like a button to expand etc. rather than a handler that extends the entire area of the ad player, but is less useful in mobile?

**Comment by gschoppe** [comment]
Do we have confirmation that this issue only effects iOS devices?

From the description this bug seems to have the potential to negatively impact any touch-capable device, including those that also offer mouse support. I would generally prefer to see this bug solved via pointer events (with a polyfill for older browsers), so as to make sure it will not affect any devices, current or future.
