### ISSUE TITLE
locale for Chinese (simplified vs traditional) documentation in README is misleading

### ISSUE THREAD

**Issue by eunicekokor** [googleads/videojs-ima#824]
Looking at the locale section, `Locale for ad localization. This may be any, ISO 639-1 (two-letter) or ISO 639-2,(three-letter) code(4). Defaults to 'en'.`. It seems like there are many Chinese localization options, and while using the `ISO 639-2` standard `zho` or `chi` resulted in no translations, `zh-Hans-TW`, `zh-Hant-CN` etc... which I have found on https://www.iana.org/assignments/language-tags/language-tags.xml contribute to my understanding that there's a different data source for this that is not `ISO 639-2`. 

It's important to us since we have users in both Taiwan and China, so we'd like to tailor the video ad experience as best as we can, and updating this documentation would help others figure out the same thing!

**Comment by Kiro705** [comment]
Hello @eunicekokor,

Thanks for raising this issue. It looks like an update to our README could definitely help with this issue.

It turns out we support only the ISO 639-1 (two-letter) codes, but have some modifications to the codes detailed in https://www.loc.gov/standards/iso639-2/php/English_list.php

To specify Taiwan or China, use the following codes `zh_tw` and `zh_cn`
Let me know if that works for you, and expect an update to our docs to clarify this in the next few days.

Thanks,
Jackson
IMA SDK DevRel

**Comment by Kiro705** [comment]
Closing the issue,

Please see our updated guide, [Localizing for Language and Locale](https://developers.google.com/interactive-media-ads/docs/sdks/html5/localization), for more info on locale codes.
