### ISSUE TITLE
Ad response empty ONLY on iframe embed.  Loading player directly shows ad.

### ISSUE THREAD

**Issue by bcorvino** [googleads/videojs-ima#876]
Hi,

We recently noticed an issue with no code change wherein our ad responses come back consistently empty on remotely embedded players, but playback correctly when the embedded player is loaded in a web page.  You can see the bug in action at:

https://www.primarygames.com/videos/category/cartoons/kitnkate/thekittykittybop/

(no ad)

vs the player embedded on that page:
http://p.batterypop.net/player/content/current_index.html?distribution_id=3c749a02-0d69-4b1d-f1a1-5c394c04145e&ms_uuid=f6794ab9-4b06-5bee-81c9-d457436ceec1&mi_uuid=a34fc4bb-1810-7668-1bb5-ecc432f0c715&autoplay=true

which does play an ad (ad response not empty).

Looking for any guidance on this issue.  Thanks!

**Comment by bcorvino** [comment]
Sorry that close was an error.  Thank you for looking into this!

**Comment by arnaudcasame** [comment]
Hi,

I was able to reproduce the behavior that you're seeing with the empty vast being returned. However, the issue is not with the videojs-ima plugin, it's an ad serving issue, the ad server returns an empty VAST XML when the ad request comes primarygames.com and not from the batterypop.net website. We would recommend you to reach out to your ad provider so they can help you fix it.

**Comment by bcorvino** [comment]
Hi Arnaud,

Almost correct.  Turns out DFP had changed its COPPA rules and ad trafficing team hadn't updated the tag correctly.  Same behavior, different cause.  Thank you so much for your attention to this.

Bill
