### ISSUE TITLE
Auto loop breaks VMAP timeOffset='end'

### ISSUE THREAD

**Issue by AaronHernandezPerez** [googleads/videojs-ima#890]
When the player loop is set to true, the final ad doesn't trigger. It works perfectly without loop.

**Comment by arnaudcasame** [comment]
Hi,

It sounds like an content event issue, I'm saying this because the SDK needs to be notified that the Content playback is completed before requesting and displaying the Post-Roll. Can you confirm whether or not the `ended` event of your player was fired with auto loop feature on?

**Comment by AaronHernandezPerez** [comment]
Effectively the event 'ended' doesn't trigger when the player is on auto loop, is it intended? and if so how should we trigger the 'end' ad when it is on auto loop?

**Comment by Kiro705** [comment]
Hi @AaronHernandezPerez ,

I believe it is intended that there is not `ended` event in a looped video. In the [videoJS docs](https://docs.videojs.com/docs/guides/options.html) it recommends using the loop option for background video, not content video. Because of that, it is a little complected to implement the solution.

To play post-roll we need to call [adsLoader.contentComplete()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.AdsLoader#contentComplete) please see the below code for more details. Note that this code for me was built as part of a constructor and uses the `this` keyword, but your implementation may not.

```
var postRollPlayed = false; //Boolean to only call contentComplete() once.

this.player.on('ads-loader', function(res){
    this.adsLoader = res.adsLoader;
  }.bind(this));

this.player.on('timeupdate', function(){
    if(this.player.remainingTime() <= 0.5) { // within half a second to the end. 
    // When looping remainingTime() never reached 0.
      if(this.adsLoader && !postRollPlayed) {
        postRollPlayed = true;
        this.adsLoader.contentComplete();
      }
    }
  }.bind(this));
```

Let me know if that works for you, or if you have any questions.

**Comment by AaronHernandezPerez** [comment]
All right thanks for the help!
