### ISSUE TITLE
Videojs IMA SDK get/set volume and mute/mute on player volume change

### ISSUE THREAD

**Issue by sunilstg** [googleads/videojs-ima#901]
Hi, 

I have tried a lot but not able to find the solution where I can do change volume of player and same need to update on vidoejs ima sdk ads volume along with mute/unmute. 

However I have tried below two params and it is doing unmute video but controlbar UI not updating. 
player.ima..controller.onAdMuteClick(); // Button changes from mute to unmute but yellow bar not increased as per volume.  
player.ima.controller.setVolume(0.8); // Nothing changes on controlbar UI. 

Please advise main methods where I can do mute/unmute and set/get volume for Videojs IMA Ads. 

Thanks

**Comment by arnaudcasame** [comment]
Hi,

Our Videojs-IMA plugin samples has volume change, mute and unmute already implemented, you can take a look and play around with them [here](https://googleads.github.io/videojs-ima/)

**Comment by sunilstg** [comment]
Hi,

Thanks a lot for your valuable time and support. Can you please advise the
function name where I can update mute and unmute to ads along with videojs
player instance. i.e. player.ima(options); player.volume=0.6; can this
volume be changed to ads also.

One more things, I have added tap to unmute button on top video player so
when ever user click on tap to unmute button it should unmute both videojs
and ads ima so please share the function/methods name where I can do
control both volume from one common function.

Also can you please advise how to serve custom midroll? i.e. on 30 seconds
of video play back I want to request midroll ads so please advise on this.

Best regards,
Sunil

**Comment by arnaudcasame** [comment]
Hi @sunilstg,

The videojs-ima plugin already takes care of muting and unmuting the ad playback when a user tap on the speaker icon.
You can use [VMAP ](https://iabtechlab.com/wp-content/uploads/2016/04/VMAP.pdf) to serve midroll but you would have to configure your timeOffset attribute so that your mid-roll can show after 30 seconds. Feel free to reach out to the [Ad Manager Support](https://support.google.com/admanager/?hl=en#topic=7505988) team so they can help you with the server-side settings.
