### ISSUE TITLE
examples of mid and post roll

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#913]
Hi

Is there any examples / pointers on how to do mid and post roll ads with videojs-ima and contrib ads.  I'm drawing an absolute blank on how to do them so far, I have pre-rolls working, just not a clue on mid and post roll  ( ideally a 2 mid roll setup)

**Comment by Kiro705** [comment]
Hello @spormeon ,

I have tested in the [videoJS-ima Advanced Example](https://googleads.github.io/videojs-ima/examples/advanced/) with this [VMAP ad](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=) containing pre, mid, and post-roll. Ads played back successfully. Does that ad fail to play mid and post-rolls in your setup?

You can find other ad tags to test with in the [IMA's sample tag page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags).

**Comment by spormeon** [comment]
my setup is prebid, which only returns vast

**Comment by Kiro705** [comment]
Hello @spormeon ,

I have confirmed that the sample [post-roll ad](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=) also works for the advanced example. Do you have an example mid or post-roll ad that is failing?

**Comment by spormeon** [comment]
basically i'm using prebid,  i can get a "tag" back from prebid with contrib ads, that looks like this:
https://securepubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&output=vast&unviewed_position_start=1&correlator=1595512070145&sz=640x480&url=https%3A%2F%2Fwww.twentyfournews.com%2Freaders-blog&iu=/1001824/Video-Corner-Units/twentyfournews.com&description_url=https%3A%2F%2Ftwentyfournews.com&cust_params=hb_uuid%3Dundefined%26hb_cache_id%3Dundefined


i take that url whihc is generated and insert it into ima, like this:

![prebid-config_obv_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/88295306-29e2ba80-ccf5-11ea-87af-6e7b3758081e.png)

![prebid-config_obv_js_—_Prebid_Publishers__Workspace_-2](https://user-images.githubusercontent.com/8503167/88295320-2ea76e80-ccf5-11ea-8487-7905d27b6490.png)


but as you can prob tell, i aint very good at this stuff, noobie.  I cant work out how to do mid and post rolls though?  first hurdle is getting it working i guess, then next hurdle would be so as prebid bids o each pre, mid and post roll?

**Comment by Kiro705** [comment]
Hi @spormeon ,

I am able to help you with implementing the videojs-ima plugin so that it can handle mid and post-roll, however I am unable to help debug issues with with what types of ads are being returned by Google Ads Manager. This Ad Manager guide on[Target video line items to positions](https://support.google.com/admanager/answer/176084?hl=en) may be able to assist with that.

In terms of support I can provide, can you verify if your IMA implementation can correctly play this [VMAP ad tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=) containing pre, mid, and post-roll ads?

**Comment by spormeon** [comment]
ye, i can play that vmap file.  I've actually revolved on since asking this question, I can get my own vmap file to play now as well, so got pre, mid and post working in effect

**Comment by Kiro705** [comment]
Based on that, it sounds like I can close this issue. Please feel free to reopen if the problem continues.
