### ISSUE TITLE
what are the options on vpaidMode , no info in any docs

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#918]
what are the options on vpaidMode , no info in any docs

default=secure

vpaidMode: INSECURE    don't work, throws error:

prebid-config.obv.js:5 Uncaught (in promise) ReferenceError: INSECURE is not defined

**Comment by Kiro705** [comment]
Hello @spormeon ,

Here is the IMA documentation for [vpaidMode and its options](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima#.VpaidMode).

Please let me know if you have farther questions.

**Comment by spormeon** [comment]
INSECURE  doesn't work as I put above:  Its turned off in this screenshot but when on, it errors as above:

![prebid-config_obv_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/88849016-295c8f00-d1e1-11ea-9b2d-12f83fa7578b.png)

**Comment by Kiro705** [comment]
Please see this line from the [IMA SDK HTML5 advanced example](https://github.com/googleads/googleads-ima-html5/blob/master/advanced/ads.js#L14) that highlights how to use setVpaidMode.

For your IMA implementation, the line would look like:
```
vpaidMode: google.ima.ImaSdkSettings.VpaidMode.ENABLED,
```

Please let me know if that helps resolve the issue.

**Comment by spormeon** [comment]
so like this?

![prebid-config_obv_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/88850744-b0126b80-d1e3-11ea-8662-ac3522d994cb.png)

**Comment by Kiro705** [comment]
Yes, that looks correct, except for one small change.

My original response set vpaidMode to `ENABLED` because I copied it from the advanced example. I have now edited my response to set it to `INSECURE`. Please also change it to `INSECURE` if that is how you wish to set vpaidMode.

**Comment by spormeon** [comment]
ye sure, i worked that out, thanks

**Comment by dioramayuanito** [comment]
i always use integer value for vpaidMode option.
0 for disable.
1 for enable secure iframe mode as a default.
2 for enable insecure iframe mode (not recommended but i can use it if some adnetwork vpaid fail to run some vpaid campaigns)

cmiiw

**Comment by spormeon** [comment]
@dioramayuanito    do you keep switching it to different ones then?, or leave on 2 all the time.   I'm seeing vpaid errors on tags/ suppliers, thats why i'm looking into this

**Comment by Kiro705** [comment]
Hello @dioramayuanito ,

It is not recommended to use the value of the variable, but instead the variable itself (`google.ima.ImaSdkSettings.VpaidMode.INSECURE` in this case).

The reason being, the IMA engineering team expects its users to use the variable, and may change the associated value without updating the [IMA release history](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/history). I wanted to bring this up, because I have seen this lead to critical issue for publishers in the past.

**Comment by dioramayuanito** [comment]
i have a "feeling", that running my player in vpaidMode:2 will make a vpaid campaign get a bigger chance to run properly, because insecure iframe mode run in a non-proxy-player mode.
But i only switch vpaidMode:1 into vpaidMode:2 if our campaign manager told us that we have a problem in his/her campaign.

**Comment by spormeon** [comment]
ok , got it,  i cant be doing that 99% is programmatic stuff, so i'd be sitting there all day switch between the things, that aint sustainable

**Comment by dioramayuanito** [comment]
ok, i will change it
