### ISSUE TITLE
Low AdX-Demand

### ISSUE THREAD

**Issue by saringer** [googleads/videojs-ima#989]
Hi Ima-Team,

my publisher noticed a decreasing AdX-Demand for our platform and I'm currently looking for the issue.

Our AD-Tag looks like this (with the description url changing for the respective watched movie):

`https://pubads.g.doubleclick.net/gampad/ads?iu=/27665794/Netzkino/Netzkino_Web&description_url=https%3A%2F%2Fwww.netzkino.de%2F%23!%2Ffilme%2Fwake-of-death&tfcd=0&npa=0&sz=640x480&cmsid=2526549&vid=737663&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=`

I just noticed when testing the [VideoJS Advanced Sample](https://googleads.github.io/videojs-ima/examples/advanced/) that either the same Ad is loaded twice (skipping the 1of5 ad-countdown to 2of2 after the first ad) or mostly none at all after reloading the page (as in the screenshot appended)

![Screenshot 2021-04-06 at 15 07 57](https://user-images.githubusercontent.com/7473273/113715587-f6608880-96e9-11eb-975e-2f749a624ed2.png)

When testing the same AD-Tag on the [Video Suite Inspector ](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) different Ads are displayed and the Ad-Countdown stays unchanged. Additionally ads were always displayed, regardless of how often I reloaded the page for loading the Pre-Rolls.

What could cause this difference in Ad-Demand when loading the Tag via Videojs-Ima or the Video-Suite-Inspector?

**Comment by Kiro705** [comment]
Hello @saringer ,

Thanks for raising this issue. Of hand I am not sure what could be causing the difference between players.

When I tested the ad tag on the [video-JS example](https://googleads.github.io/videojs-ima/examples/advanced/) and was not able to reproduce the example. Every time I reloaded the page either 4 or 5 different ads were loaded and played as pre-roll.

Was there any change to the ad tag or settings in ad manager to fix this?

If this issue is still happening for you, I may need additional clarification on steps to reproduce the issue.

Thank you,
Jackson
IMA SDK Team
