### ISSUE TITLE
Early post-roll calls

### ISSUE THREAD

**Issue by skullhole** [googleads/videojs-ima#991]
Hello team, 

I have been inspecting the advanced example here https://googleads.github.io/videojs-ima/examples/advanced/
with "VMAP Pre-, Mid-, and Post-rolls, Single Ads" tag from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags#vmap-pre-,-mid-,-and-post-rolls,-single-ads
```
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=
```
and i am seeing that the call to `https://pubads.g.doubleclick.net/gampad/ads?slotname=...` with `vpos=postroll` is being made shortly after the midroll ends which is long before the video completion.

![image](https://user-images.githubusercontent.com/1258137/115179730-30745600-a0fe-11eb-960b-18f145958390.png)

That call look to happen very early considering that potentially significant amount of the users might not be getting to the video completion making that call a wasted one. 

Is this by the design?
Are there ways to control when these calls are made and make them at the later time? 

Thanks.

**Comment by Kiro705** [comment]
Hello @skullhole ,

This is by design, IMA will load the post-roll following the last midroll ad. Because this is not specific to the VideoJS-IMA plugin but the behavior of the IMA SDK in general, I would ask you to raise the request to change this behavior on the [IMA SDK forum](https://groups.google.com/g/ima-sdk). The request will be properly routed to the team from there.

Thank you,
Jackson
IMA SDK Team
